// Code generated by goninja generate. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strings"

	"github.com/caspel26/goninja"
	"github.com/caspel26/goninja/id"
	"github.com/caspel26/goninja/mw"
	"github.com/caspel26/goninja/openapi"
	"github.com/caspel26/goninja/pagination"
	"github.com/caspel26/goninja/validate"
	"gorm.io/gorm"

	"github.com/caspel26/goninja/examples/prototype/models"
)

// AuthorList is the shape returned by GET /authors,
// one item per row of the "items" field of pagination.ListEnvelope.
type AuthorList struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// AuthorRetrieve is the shape returned by GET /authors/{id}.
// A relation field (e.g. Author) is nested as that model's own Retrieve
// type, never the raw related struct — output types are always separate
// from the model, so a sensitive field can't leak into a response just
// because it exists on the related struct either. A relation field tagged
// "byid" (plan section 5.12) instead exposes only the related model's ID,
// as "<field>_id" — no nesting, no Preload.
type AuthorRetrieve struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Bio  string `json:"bio"`
}

// AuthorCreate is the shape accepted by POST /authors.
// `validate` tags (go-playground/validator syntax) are copied verbatim from
// the model field's own `validate` tag, and enforced by validate.Validate
// before Create runs.
type AuthorCreate struct {
	Name string `json:"name" validate:"required,max=120"`
	Bio  string `json:"bio" validate:"max=2000"`
}

// AuthorUpdate is the shape accepted by PUT /authors/{id}.
type AuthorUpdate struct {
	Name string `json:"name" validate:"required,max=120"`
	Bio  string `json:"bio" validate:"max=2000"`
}

// AuthorFilters is the shape parsed from GET /authors
// query parameters (plan section 5.5/Fase 4): one exact-match pointer field
// per `filter`-tagged model field, plus Min/Max range pointers for numeric
// ones, plus Limit/Offset/Order shared by every model's list query. A nil
// field means "no filter" — List only adds a WHERE clause for the ones the
// caller actually set.
type AuthorFilters struct {
	Name   *string
	Limit  int
	Offset int
	// Order is a list-field JSON name, optionally "-"-prefixed for
	// descending (e.g. "-created_at"). Unknown field names are ignored.
	Order string
}

// authorOrderableColumns whitelists which query values
// "order" accepts — every list field, keyed and valued by its JSON name
// (assumed to match the actual DB column, per this model's `json` tags).
// Only ever indexed with a known key, never interpolated from user input
// directly, so this doubles as the SQL-injection guard for ORDER BY.
var authorOrderableColumns = map[string]string{
	"id":   "id",
	"name": "name",
}

func toAuthorList(m *models.Author) AuthorList {
	return AuthorList{
		ID:   m.ID,
		Name: m.Name,
	}
}

func toAuthorRetrieve(m *models.Author) AuthorRetrieve {
	return AuthorRetrieve{
		ID:   m.ID,
		Name: m.Name,
		Bio:  m.Bio,
	}
}

// AuthorResource is the generated GORM-backed CRUD resource for
// Author. Embeds goninja.BaseResource for a transaction-aware
// DB(ctx) and a configurable ErrorMapper.
type AuthorResource struct {
	goninja.BaseResource
}

// NewAuthorResource builds a AuthorResource bound to db.
func NewAuthorResource(db *gorm.DB) *AuthorResource {
	r := &AuthorResource{}
	r.SetDB(db)
	r.SetSelf(r)
	return r
}

// AuthorOps is the method set the generated handlers dispatch
// every request through. A type embedding AuthorResource and
// overriding one of these methods (plan section 5.10) is picked up
// automatically once wired in via SetSelf — see ops() below.
type AuthorOps interface {
	List(ctx context.Context, f AuthorFilters) ([]AuthorList, int64, error)
	Retrieve(ctx context.Context, id string) (*AuthorRetrieve, error)
	Create(ctx context.Context, in AuthorCreate) (*AuthorRetrieve, error)
	Update(ctx context.Context, id string, in AuthorUpdate) (*AuthorRetrieve, error)
	Delete(ctx context.Context, id string) error
}

// ops returns the AuthorOps the generated handlers should call:
// r.Self() if it satisfies the interface (a wrapper type overriding one or
// more methods), otherwise r itself. r.Self() is r by default (set by
// NewAuthorResource), so this is a no-op unless SetSelf was
// called again with a different value.
func (r *AuthorResource) ops() AuthorOps {
	if o, ok := r.Self().(AuthorOps); ok {
		return o
	}
	return r
}

// List applies f's filters/ordering, counts the total matching rows before
// paginating, and returns Limit/Offset rows plus that total — never a
// Preload, by construction, which is why list/retrieve are separate tags
// (plan section 5.5): it's the guarantee against N+1, not an
// implementation detail.
func (r *AuthorResource) List(ctx context.Context, f AuthorFilters) ([]AuthorList, int64, error) {
	q := r.DB(ctx).Model(&models.Author{})
	if f.Name != nil {
		q = q.Where("name = ?", *f.Name)
	}

	var total int64
	if err := q.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	if f.Order != "" {
		field, desc := strings.CutPrefix(f.Order, "-")
		if col, ok := authorOrderableColumns[field]; ok {
			dir := "ASC"
			if desc {
				dir = "DESC"
			}
			q = q.Order(col + " " + dir)
		}
	}

	var items []models.Author
	if err := q.Limit(f.Limit).Offset(f.Offset).Find(&items).Error; err != nil {
		return nil, 0, err
	}
	out := make([]AuthorList, 0, len(items))
	for i := range items {
		out = append(out, toAuthorList(&items[i]))
	}
	return out, total, nil
}

// Retrieve preloads every relation field carried on the retrieve type —
// list never does, by construction (see List above) — except one tagged
// "byid" (plan section 5.12), which exposes only the related ID and so
// skips the Preload entirely.
func (r *AuthorResource) Retrieve(ctx context.Context, id string) (*AuthorRetrieve, error) {
	q := r.DB(ctx)

	var m models.Author
	if err := q.First(&m, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "author", ID: id}
		}
		return nil, err
	}
	out := toAuthorRetrieve(&m)
	return &out, nil
}

func (r *AuthorResource) Create(ctx context.Context, in AuthorCreate) (*AuthorRetrieve, error) {
	if err := validate.Validate(in); err != nil {
		return nil, err
	}
	m := models.Author{
		Name: in.Name,
		Bio:  in.Bio,
	}
	if m.ID == "" {
		m.ID = id.NewUUID()
	}
	if err := r.DB(ctx).Create(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, m.ID)
}

func (r *AuthorResource) Update(ctx context.Context, id string, in AuthorUpdate) (*AuthorRetrieve, error) {
	if err := validate.Validate(in); err != nil {
		return nil, err
	}
	var m models.Author
	if err := r.DB(ctx).First(&m, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "author", ID: id}
		}
		return nil, err
	}
	m.Name = in.Name
	m.Bio = in.Bio
	if err := r.DB(ctx).Save(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, id)
}

func (r *AuthorResource) Delete(ctx context.Context, id string) error {
	res := r.DB(ctx).Where("id = ?", id).Delete(&models.Author{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return goninja.NotFound{Resource: "author", ID: id}
	}
	return nil
}

// parseAuthorFilters reads AuthorFilters from the request's
// query parameters, keyed by each field's JSON name (plus "_min"/"_max" for
// numeric range filters). A value that fails to parse is a BadRequest.
func parseAuthorFilters(req *http.Request) (AuthorFilters, error) {
	q := req.URL.Query()
	var f AuthorFilters

	if v := q.Get("name"); v != "" {
		parsed := v
		f.Name = &parsed
	}

	limit, offset, err := pagination.ParseLimitOffset(q)
	if err != nil {
		return f, err
	}
	f.Limit = limit
	f.Offset = offset
	f.Order = q.Get("order")

	return f, nil
}

func (r *AuthorResource) listHandler(w http.ResponseWriter, req *http.Request) {
	f, err := parseAuthorFilters(req)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	items, total, err := r.ops().List(req.Context(), f)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, pagination.ListEnvelope[AuthorList]{
		Items:  items,
		Total:  total,
		Limit:  f.Limit,
		Offset: f.Offset,
	})
}

func (r *AuthorResource) retrieveHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}

	out, err := r.ops().Retrieve(req.Context(), id)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// createHandler runs BeforeCreateHook/AfterCreateHook (hooks.go), if r's
// Self() implements them, in the same transaction as the create itself —
// a hook returning an error rolls the whole request back (plan section
// 5.6/5.7).
func (r *AuthorResource) createHandler(w http.ResponseWriter, req *http.Request) {
	var in AuthorCreate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*AuthorRetrieve, error) {
		if h, ok := self.(goninja.BeforeCreateHook[AuthorCreate]); ok {
			if err := h.BeforeCreate(ctx, &in); err != nil {
				return nil, err
			}
		}
		created, err := ops.Create(ctx, in)
		if err != nil {
			return nil, err
		}
		if h, ok := self.(goninja.AfterCreateHook[AuthorRetrieve]); ok {
			if err := h.AfterCreate(ctx, created); err != nil {
				return nil, err
			}
		}
		return created, nil
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusCreated, out)
}

// updateHandler runs BeforeUpdateHook (hooks.go), if r's Self() implements
// it, in the same transaction as the update itself.
func (r *AuthorResource) updateHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}

	var in AuthorUpdate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*AuthorRetrieve, error) {
		if h, ok := self.(goninja.BeforeUpdateHook[AuthorUpdate]); ok {
			if err := h.BeforeUpdate(ctx, &in); err != nil {
				return nil, err
			}
		}
		return ops.Update(ctx, id, in)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// deleteHandler runs BeforeDeleteHook (hooks.go), if r's Self() implements
// it, in the same transaction as the delete itself.
func (r *AuthorResource) deleteHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}

	self, ops := r.Self(), r.ops()
	_, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (struct{}, error) {
		if h, ok := self.(goninja.BeforeDeleteHook[string]); ok {
			if err := h.BeforeDelete(ctx, id); err != nil {
				return struct{}{}, err
			}
		}
		return struct{}{}, ops.Delete(ctx, id)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// OpenAPI returns this resource's fragment of a merged OpenAPI document
// (plan section 5.10/Fase 5) — the paths it mounts and the schemas those
// paths reference, built from the same IR as the rest of this file, so
// they always match what List/Retrieve/Create/Update actually accept and
// return. Pass this resource to an openapi.API's Add method (alongside its
// Register(mux) call) to merge it in; see docsui.MountDocs.
func (r *AuthorResource) OpenAPI() (map[string]*openapi.PathItem, map[string]openapi.Schema) {
	tags := r.OpenAPITags()
	if len(tags) == 0 {
		tags = []string{"Author"}
	}

	schemas := map[string]openapi.Schema{
		"AuthorList": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"id":   {Type: "string"},
				"name": {Type: "string"},
			},
		},
		"AuthorRetrieve": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"id":   {Type: "string"},
				"name": {Type: "string"},
				"bio":  {Type: "string"},
			},
		},
		"AuthorCreate": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"name": {Type: "string"},
				"bio":  {Type: "string"},
			},
			Required: []string{"name"},
		},
		"AuthorUpdate": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"name": {Type: "string"},
				"bio":  {Type: "string"},
			},
			Required: []string{"name"},
		},
		"AuthorListEnvelope": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"items":  {Type: "array", Items: &openapi.Schema{Ref: "#/components/schemas/AuthorList"}},
				"total":  {Type: "integer", Format: "int64"},
				"limit":  {Type: "integer"},
				"offset": {Type: "integer"},
			},
		},
	}

	listParams := []openapi.Parameter{
		{Name: "name", In: "query", Schema: openapi.Schema{Type: "string"}},
		{Name: "limit", In: "query", Schema: openapi.Schema{Type: "integer"}},
		{Name: "offset", In: "query", Schema: openapi.Schema{Type: "integer"}},
		{Name: "order", In: "query", Schema: openapi.Schema{Type: "string"}},
	}

	idParam := openapi.Parameter{
		Name:     "id",
		In:       "path",
		Required: true,
		Schema:   openapi.Schema{Type: "string"},
	}

	cfg := r.resourceConfig()
	basePath := cfg.PathOr("/authors")
	itemPath := basePath + "/{id}"

	paths := map[string]*openapi.PathItem{}

	basePathItem := &openapi.PathItem{}
	if cfg.RouteEnabled("list") {
		basePathItem.Get = &openapi.Operation{
			Summary:    "List authors",
			Tags:       tags,
			Parameters: listParams,
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					"application/json": {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorListEnvelope"}},
				}},
			},
		}
	}
	if cfg.RouteEnabled("create") {
		basePathItem.Post = &openapi.Operation{
			Summary: "Create a author",
			Tags:    tags,
			RequestBody: &openapi.RequestBody{
				Required: true,
				Content: map[string]openapi.MediaType{
					"application/json": {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorCreate"}},
				},
			},
			Responses: map[string]openapi.Response{
				"201": {Description: "Created", Content: map[string]openapi.MediaType{
					"application/json": {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorRetrieve"}},
				}},
				"422": {Description: "Validation error"},
			},
		}
	}
	if basePathItem.Get != nil || basePathItem.Post != nil {
		paths[basePath] = basePathItem
	}

	itemPathItem := &openapi.PathItem{}
	if cfg.RouteEnabled("retrieve") {
		itemPathItem.Get = &openapi.Operation{
			Summary:    "Retrieve a author",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					"application/json": {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorRetrieve"}},
				}},
				"404": {Description: "Not found"},
			},
		}
	}
	if cfg.RouteEnabled("update") {
		itemPathItem.Put = &openapi.Operation{
			Summary:    "Update a author",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			RequestBody: &openapi.RequestBody{
				Required: true,
				Content: map[string]openapi.MediaType{
					"application/json": {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorUpdate"}},
				},
			},
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					"application/json": {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorRetrieve"}},
				}},
				"404": {Description: "Not found"},
				"422": {Description: "Validation error"},
			},
		}
	}
	if cfg.RouteEnabled("delete") {
		itemPathItem.Delete = &openapi.Operation{
			Summary:    "Delete a author",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			Responses: map[string]openapi.Response{
				"204": {Description: "No content"},
				"404": {Description: "Not found"},
			},
		}
	}
	if itemPathItem.Get != nil || itemPathItem.Put != nil || itemPathItem.Delete != nil {
		paths[itemPath] = itemPathItem
	}

	return paths, schemas
}

// resourceConfig resolves r's ResourceConfig via r.Self(), the same
// dispatch hooks.go and ops() use: a wrapper implementing
// mw.Configurer (plan section 5.3) customizes it, otherwise every
// generated default applies.
func (r *AuthorResource) resourceConfig() mw.ResourceConfig {
	if c, ok := r.Self().(mw.Configurer); ok {
		return c.Config()
	}
	return mw.ResourceConfig{}
}

// Register mounts list/retrieve/create/update/delete routes for
// Author under /authors on mux, or under r's
// ResourceConfig.Path/Routes override (see resourceConfig above) if one is
// set. Every handler is wrapped through r.Protect, which applies this
// resource's Config (global default auth + generic middleware, set via
// mw.MountWithConfig — see mw/config.go) combined with cfg's own AuthOverride; a
// resource mounted via plain Mount has a zero Config, so Protect is a
// no-op there.
func (r *AuthorResource) Register(mux *http.ServeMux) {
	cfg := r.resourceConfig()
	path := cfg.PathOr("/authors")
	if cfg.RouteEnabled("list") {
		mux.HandleFunc("GET "+path, r.Protect("list", cfg, r.listHandler))
	}
	if cfg.RouteEnabled("create") {
		mux.HandleFunc("POST "+path, r.Protect("create", cfg, r.createHandler))
	}
	if cfg.RouteEnabled("retrieve") {
		mux.HandleFunc("GET "+path+"/{id}", r.Protect("retrieve", cfg, r.retrieveHandler))
	}
	if cfg.RouteEnabled("update") {
		mux.HandleFunc("PUT "+path+"/{id}", r.Protect("update", cfg, r.updateHandler))
	}
	if cfg.RouteEnabled("delete") {
		mux.HandleFunc("DELETE "+path+"/{id}", r.Protect("delete", cfg, r.deleteHandler))
	}
}
