// Code generated by goninja generate. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strings"

	"github.com/caspel26/goninja"
	"github.com/caspel26/goninja/id"
	"github.com/caspel26/goninja/openapi"
	"gorm.io/gorm"

	"github.com/caspel26/goninja/examples/prototype/models"
)

// AuthorList is the shape returned by GET /authors,
// one item per row of the "items" field of goninja.ListEnvelope.
type AuthorList struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// AuthorRetrieve is the shape returned by GET /authors/{id}.
// A relation field (e.g. Author) is nested as that model's own Retrieve
// type, never the raw related struct — output types are always separate
// from the model, so a sensitive field can't leak into a response just
// because it exists on the related struct either. A relation field tagged
// "byid" (plan section 5.12) instead exposes only the related model's ID,
// as "<field>_id" — no nesting, no Preload.
type AuthorRetrieve struct {
	ID    string         `json:"id"`
	Name  string         `json:"name"`
	Bio   string         `json:"bio"`
	Books []BookRetrieve `json:"books"`
}

// AuthorCreate is the shape accepted by POST /authors.
// `validate` tags (go-playground/validator syntax) are copied verbatim from
// the model field's own `validate` tag, and enforced by goninja.Validate
// before Create runs.
type AuthorCreate struct {
	Name string `json:"name" validate:"required,max=120"`
	Bio  string `json:"bio" validate:"max=2000"`
}

// AuthorUpdate is the shape accepted by PUT /authors/{id}.
type AuthorUpdate struct {
	Name string `json:"name" validate:"required,max=120"`
	Bio  string `json:"bio" validate:"max=2000"`
}

// AuthorFilters is the shape parsed from GET /authors
// query parameters (plan section 5.5/Fase 4): one exact-match pointer field
// per `filter`-tagged model field, plus Min/Max range pointers for numeric
// ones, plus Limit/Offset/Order shared by every model's list query. A nil
// field means "no filter" — List only adds a WHERE clause for the ones the
// caller actually set.
type AuthorFilters struct {
	Name   *string
	Limit  int
	Offset int
	// Order is a list-field JSON name, optionally "-"-prefixed for
	// descending (e.g. "-created_at"). Unknown field names are ignored.
	Order string
}

// authorOrderableColumns whitelists which query values
// "order" accepts — every list field, keyed and valued by its JSON name
// (assumed to match the actual DB column, per this model's `json` tags).
// Only ever indexed with a known key, never interpolated from user input
// directly, so this doubles as the SQL-injection guard for ORDER BY.
var authorOrderableColumns = map[string]string{
	"id":   "id",
	"name": "name",
}

// authorInvalidIDMsg/authorIDQuery/
// authorContentTypeJSON/authorNotFoundDesc/
// authorRetrieveRef are shared across this file's
// handlers/resource methods (including OpenAPI() and its helpers below) to
// avoid repeating the same literal per call site — package-level, prefixed
// per model since several models can be generated into the same output
// package.
const (
	authorInvalidIDMsg    = "invalid id"
	authorIDQuery         = "id = ?"
	authorContentTypeJSON = "application/json"
	authorNotFoundDesc    = "Not found"
	authorRetrieveRef     = "#/components/schemas/AuthorRetrieve"
)

func toAuthorList(m *models.Author) AuthorList {
	return AuthorList{
		ID:   m.ID,
		Name: m.Name,
	}
}

func toAuthorRetrieve(m *models.Author) AuthorRetrieve {
	return AuthorRetrieve{
		ID:   m.ID,
		Name: m.Name,
		Bio:  m.Bio,
		Books: func() []BookRetrieve {
			out := make([]BookRetrieve, 0, len(m.Books))
			for i := range m.Books {
				out = append(out, toBookRetrieve(&m.Books[i]))
			}
			return out
		}(),
	}
}

// AuthorResource is the generated GORM-backed CRUD resource for
// Author. Embeds goninja.BaseResource for a transaction-aware
// DB(ctx) and a configurable ErrorMapper.
type AuthorResource struct {
	goninja.BaseResource
}

// NewAuthorResource builds a AuthorResource bound to db.
func NewAuthorResource(db *gorm.DB) *AuthorResource {
	r := &AuthorResource{}
	r.SetDB(db)
	r.SetSelf(r)
	return r
}

// AuthorOps is the method set the generated handlers dispatch
// every request through. A type embedding AuthorResource and
// overriding one of these methods (plan section 5.10) is picked up
// automatically once wired in via SetSelf — see ops() below.
type AuthorOps interface {
	List(ctx context.Context, f AuthorFilters) ([]AuthorList, int64, error)
	Retrieve(ctx context.Context, id string) (*AuthorRetrieve, error)
	Create(ctx context.Context, in AuthorCreate) (*AuthorRetrieve, error)
	Update(ctx context.Context, id string, in AuthorUpdate) (*AuthorRetrieve, error)
	Delete(ctx context.Context, id string) error
}

// ops returns the AuthorOps the generated handlers should call:
// r.Self() if it satisfies the interface (a wrapper type overriding one or
// more methods), otherwise r itself. r.Self() is r by default (set by
// NewAuthorResource), so this is a no-op unless SetSelf was
// called again with a different value.
func (r *AuthorResource) ops() AuthorOps {
	if o, ok := r.Self().(AuthorOps); ok {
		return o
	}
	return r
}

// List applies f's filters/ordering, counts the total matching rows before
// paginating, and returns Limit/Offset rows plus that total — never a
// Preload, by construction, which is why list/retrieve are separate tags
// (plan section 5.5): it's the guarantee against N+1, not an
// implementation detail.
func (r *AuthorResource) List(ctx context.Context, f AuthorFilters) ([]AuthorList, int64, error) {
	q := r.DB(ctx).Model(&models.Author{})
	if f.Name != nil {
		q = q.Where("name = ?", *f.Name)
	}

	var total int64
	if err := q.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	if f.Order != "" {
		field, desc := strings.CutPrefix(f.Order, "-")
		if col, ok := authorOrderableColumns[field]; ok {
			dir := "ASC"
			if desc {
				dir = "DESC"
			}
			q = q.Order(col + " " + dir)
		}
	}

	var items []models.Author
	if err := q.Limit(f.Limit).Offset(f.Offset).Find(&items).Error; err != nil {
		return nil, 0, err
	}
	out := make([]AuthorList, 0, len(items))
	for i := range items {
		out = append(out, toAuthorList(&items[i]))
	}
	return out, total, nil
}

// Retrieve preloads every relation field carried on the retrieve type —
// list never does, by construction (see List above) — except one tagged
// "byid" (plan section 5.12), which exposes only the related ID and so
// skips the Preload entirely.
func (r *AuthorResource) Retrieve(ctx context.Context, id string) (*AuthorRetrieve, error) {
	q := r.DB(ctx)
	q = q.Preload("Books")

	var m models.Author
	if err := q.First(&m, authorIDQuery, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "author", ID: id}
		}
		return nil, err
	}
	out := toAuthorRetrieve(&m)
	return &out, nil
}

func (r *AuthorResource) Create(ctx context.Context, in AuthorCreate) (*AuthorRetrieve, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	m := models.Author{
		Name: in.Name,
		Bio:  in.Bio,
	}
	if m.ID == "" {
		m.ID = id.NewUUID()
	}
	if err := r.DB(ctx).Create(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, m.ID)
}

func (r *AuthorResource) Update(ctx context.Context, id string, in AuthorUpdate) (*AuthorRetrieve, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	var m models.Author
	if err := r.DB(ctx).First(&m, authorIDQuery, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "author", ID: id}
		}
		return nil, err
	}
	m.Name = in.Name
	m.Bio = in.Bio
	if err := r.DB(ctx).Save(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, id)
}

func (r *AuthorResource) Delete(ctx context.Context, id string) error {
	res := r.DB(ctx).Where(authorIDQuery, id).Delete(&models.Author{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return goninja.NotFound{Resource: "author", ID: id}
	}
	return nil
}

// parseAuthorFilters reads AuthorFilters from the request's
// query parameters, keyed by each field's JSON name (plus "_min"/"_max" for
// numeric range filters). A value that fails to parse is a BadRequest.
func parseAuthorFilters(req *http.Request) (AuthorFilters, error) {
	q := req.URL.Query()
	var f AuthorFilters

	if v := q.Get("name"); v != "" {
		parsed := v
		f.Name = &parsed
	}

	limit, offset, err := goninja.ParseLimitOffset(q)
	if err != nil {
		return f, err
	}
	f.Limit = limit
	f.Offset = offset

	// Reject an unknown order field here rather than ignoring it in List: a
	// typo would otherwise return the default order with a 200, which reads
	// as "sorted the way you asked" and is impossible to notice from the
	// response.
	if order := q.Get("order"); order != "" {
		field, _ := strings.CutPrefix(order, "-")
		if _, ok := authorOrderableColumns[field]; !ok {
			return f, goninja.BadRequest{
				Detail: "cannot order by \"" + field + "\"",
				Code:   "INVALID_ORDER_FIELD",
			}
		}
		f.Order = order
	}

	return f, nil
}

func (r *AuthorResource) listHandler(w http.ResponseWriter, req *http.Request) {
	f, err := parseAuthorFilters(req)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	items, total, err := r.ops().List(req.Context(), f)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, goninja.ListEnvelope[AuthorList]{
		Items:  items,
		Total:  total,
		Limit:  f.Limit,
		Offset: f.Offset,
	})
}

func (r *AuthorResource) retrieveHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: authorInvalidIDMsg})
		return
	}

	out, err := r.ops().Retrieve(req.Context(), id)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// createHandler runs BeforeCreateHook/AfterCreateHook (hooks.go), if r's
// Self() implements them, in the same transaction as the create itself —
// a hook returning an error rolls the whole request back (plan section
// 5.6/5.7).
func (r *AuthorResource) createHandler(w http.ResponseWriter, req *http.Request) {
	var in AuthorCreate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*AuthorRetrieve, error) {
		if h, ok := self.(goninja.BeforeCreateHook[AuthorCreate]); ok {
			if err := h.BeforeCreate(ctx, &in); err != nil {
				return nil, err
			}
		}
		created, err := ops.Create(ctx, in)
		if err != nil {
			return nil, err
		}
		if h, ok := self.(goninja.AfterCreateHook[AuthorRetrieve]); ok {
			if err := h.AfterCreate(ctx, created); err != nil {
				return nil, err
			}
		}
		return created, nil
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusCreated, out)
}

// updateHandler runs BeforeUpdateHook (hooks.go), if r's Self() implements
// it, in the same transaction as the update itself.
func (r *AuthorResource) updateHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: authorInvalidIDMsg})
		return
	}

	var in AuthorUpdate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*AuthorRetrieve, error) {
		if h, ok := self.(goninja.BeforeUpdateHook[AuthorUpdate]); ok {
			if err := h.BeforeUpdate(ctx, &in); err != nil {
				return nil, err
			}
		}
		return ops.Update(ctx, id, in)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// deleteHandler runs BeforeDeleteHook (hooks.go), if r's Self() implements
// it, in the same transaction as the delete itself.
func (r *AuthorResource) deleteHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: authorInvalidIDMsg})
		return
	}

	self, ops := r.Self(), r.ops()
	_, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (struct{}, error) {
		if h, ok := self.(goninja.BeforeDeleteHook[string]); ok {
			if err := h.BeforeDelete(ctx, id); err != nil {
				return struct{}{}, err
			}
		}
		return struct{}{}, ops.Delete(ctx, id)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// OpenAPI returns this resource's fragment of a merged OpenAPI document —
// the paths it mounts, the schemas those paths reference, and the security
// schemes any protected path's Security refers to (resolved via
// r.SecurityFor, the same logic Register's r.Protect calls enforce, so the
// two can't drift apart) — built from the same IR as the rest of this
// file, so they always match what List/Retrieve/Create/Update actually
// accept and return. Pass this resource to a goninja.API's Add method
// (alongside its Register(mux) call) to merge it in, or just pass it to
// API.Mount; see API.MountDocs.
func (r *AuthorResource) OpenAPI() (map[string]*openapi.PathItem, map[string]openapi.Schema, map[string]openapi.SecurityScheme) {
	tags := r.OpenAPITags()
	if len(tags) == 0 {
		tags = []string{"Author"}
	}

	schemas := map[string]openapi.Schema{
		"AuthorList": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"id":   {Type: "string"},
				"name": {Type: "string"},
			},
		},
		"AuthorRetrieve": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"id":    {Type: "string"},
				"name":  {Type: "string"},
				"bio":   {Type: "string"},
				"books": {Type: "array", Items: &openapi.Schema{Ref: "#/components/schemas/BookRetrieve"}},
			},
		},
		"AuthorCreate": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"name": {Type: "string"},
				"bio":  {Type: "string"},
			},
			Required: []string{"name"},
		},
		"AuthorUpdate": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"name": {Type: "string"},
				"bio":  {Type: "string"},
			},
			Required: []string{"name"},
		},
		"AuthorListEnvelope": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"items":  {Type: "array", Items: &openapi.Schema{Ref: "#/components/schemas/AuthorList"}},
				"total":  {Type: "integer", Format: "int64"},
				"limit":  {Type: "integer"},
				"offset": {Type: "integer"},
			},
		},
	}

	listParams := []openapi.Parameter{
		{Name: "name", In: "query", Schema: openapi.Schema{Type: "string"}},
		{Name: "limit", In: "query", Schema: openapi.Schema{Type: "integer"}},
		{Name: "offset", In: "query", Schema: openapi.Schema{Type: "integer"}},
		{Name: "order", In: "query", Schema: openapi.Schema{Type: "string"}},
	}

	idParam := openapi.Parameter{
		Name:     "id",
		In:       "path",
		Required: true,
		Schema:   openapi.Schema{Type: "string"},
	}

	cfg := r.resourceConfig()
	basePath := cfg.PathOr("/authors")
	itemPath := basePath + "/{id}"

	paths := map[string]*openapi.PathItem{}
	securitySchemes := map[string]openapi.SecurityScheme{}

	if item := r.openAPIBasePathItem(cfg, tags, listParams, securitySchemes); item != nil {
		paths[basePath] = item
	}
	if item := r.openAPIItemPathItem(cfg, tags, idParam, securitySchemes); item != nil {
		paths[itemPath] = item
	}
	r.openAPIActionPaths(paths, basePath, idParam, tags, cfg, securitySchemes)

	return paths, schemas, securitySchemes
}

// openAPISecurity resolves route's Security requirement via r.SecurityFor
// and, if non-nil, merges its referenced SecurityScheme(s) into schemes —
// shared by every op builder below so each documents exactly what
// r.Protect enforces for that route.
func (r *AuthorResource) openAPISecurity(route goninja.Route, cfg goninja.ResourceConfig, schemes map[string]openapi.SecurityScheme) []map[string][]string {
	reqs, s := r.SecurityFor(route, cfg)
	for name, scheme := range s {
		schemes[name] = scheme
	}
	return reqs
}

// openAPIBasePathItem builds the list/create *openapi.PathItem for
// "authors" (nil if neither route is enabled) — split out of
// OpenAPI() to keep its cognitive complexity in check.
func (r *AuthorResource) openAPIBasePathItem(cfg goninja.ResourceConfig, tags []string, listParams []openapi.Parameter, schemes map[string]openapi.SecurityScheme) *openapi.PathItem {
	item := &openapi.PathItem{}
	if cfg.RouteEnabled(goninja.RouteList) {
		item.Get = &openapi.Operation{
			Summary:    "List authors",
			Tags:       tags,
			Parameters: listParams,
			Security:   r.openAPISecurity(goninja.RouteList, cfg, schemes),
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					authorContentTypeJSON: {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorListEnvelope"}},
				}},
			},
		}
	}
	if cfg.RouteEnabled(goninja.RouteCreate) {
		item.Post = &openapi.Operation{
			Summary:  "Create a author",
			Tags:     tags,
			Security: r.openAPISecurity(goninja.RouteCreate, cfg, schemes),
			RequestBody: &openapi.RequestBody{
				Required: true,
				Content: map[string]openapi.MediaType{
					authorContentTypeJSON: {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorCreate"}},
				},
			},
			Responses: map[string]openapi.Response{
				"201": {Description: "Created", Content: map[string]openapi.MediaType{
					authorContentTypeJSON: {Schema: openapi.Schema{Ref: authorRetrieveRef}},
				}},
				"422": {Description: "Validation error"},
			},
		}
	}
	if item.Get == nil && item.Post == nil {
		return nil
	}
	return item
}

// openAPIItemPathItem builds the retrieve/update/delete *openapi.PathItem
// for "authors/{id}" (nil if none of the three routes is
// enabled) — split out of OpenAPI() to keep its cognitive complexity in
// check.
func (r *AuthorResource) openAPIItemPathItem(cfg goninja.ResourceConfig, tags []string, idParam openapi.Parameter, schemes map[string]openapi.SecurityScheme) *openapi.PathItem {
	item := &openapi.PathItem{}
	if cfg.RouteEnabled(goninja.RouteRetrieve) {
		item.Get = &openapi.Operation{
			Summary:    "Retrieve a author",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			Security:   r.openAPISecurity(goninja.RouteRetrieve, cfg, schemes),
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					authorContentTypeJSON: {Schema: openapi.Schema{Ref: authorRetrieveRef}},
				}},
				"404": {Description: authorNotFoundDesc},
			},
		}
	}
	if cfg.RouteEnabled(goninja.RouteUpdate) {
		item.Put = &openapi.Operation{
			Summary:    "Update a author",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			Security:   r.openAPISecurity(goninja.RouteUpdate, cfg, schemes),
			RequestBody: &openapi.RequestBody{
				Required: true,
				Content: map[string]openapi.MediaType{
					authorContentTypeJSON: {Schema: openapi.Schema{Ref: "#/components/schemas/AuthorUpdate"}},
				},
			},
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					authorContentTypeJSON: {Schema: openapi.Schema{Ref: authorRetrieveRef}},
				}},
				"404": {Description: authorNotFoundDesc},
				"422": {Description: "Validation error"},
			},
		}
	}
	if cfg.RouteEnabled(goninja.RouteDelete) {
		item.Delete = &openapi.Operation{
			Summary:    "Delete a author",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			Security:   r.openAPISecurity(goninja.RouteDelete, cfg, schemes),
			Responses: map[string]openapi.Response{
				"204": {Description: "No content"},
				"404": {Description: authorNotFoundDesc},
			},
		}
	}
	if item.Get == nil && item.Put == nil && item.Delete == nil {
		return nil
	}
	return item
}

// openAPIActionPaths adds a path entry for every r.Actions() action that
// carries a Summary, mounted the same way Register mounts it (base or
// "/{id}"-suffixed, then UrlPath) — split out of OpenAPI() to keep its
// cognitive complexity in check.
func (r *AuthorResource) openAPIActionPaths(paths map[string]*openapi.PathItem, basePath string, idParam openapi.Parameter, tags []string, cfg goninja.ResourceConfig, schemes map[string]openapi.SecurityScheme) {
	for _, a := range r.Actions() {
		if a.Summary == "" {
			continue
		}
		p := basePath
		if a.Detail {
			p += "/{id}"
		}
		if a.UrlPath != "" {
			p += "/" + a.UrlPath
		}
		item, ok := paths[p]
		if !ok {
			item = &openapi.PathItem{}
			paths[p] = item
		}
		op := &openapi.Operation{Summary: a.Summary, Tags: tags, Responses: a.Responses, Security: r.openAPISecurity(goninja.Route(a.Name), cfg, schemes)}
		if a.Detail {
			op.Parameters = []openapi.Parameter{idParam}
		}
		switch a.Method {
		case http.MethodGet:
			item.Get = op
		case http.MethodPost:
			item.Post = op
		case http.MethodPut:
			item.Put = op
		case http.MethodDelete:
			item.Delete = op
		}
	}
}

// resourceConfig resolves r's ResourceConfig via r.Self(), the same
// dispatch hooks.go and ops() use: a wrapper implementing
// goninja.Configurer (plan section 5.3) customizes it, otherwise every
// generated default applies.
func (r *AuthorResource) resourceConfig() goninja.ResourceConfig {
	if c, ok := r.Self().(goninja.Configurer); ok {
		return c.Config()
	}
	return goninja.ResourceConfig{}
}

// Register mounts list/retrieve/create/update/delete routes for
// Author under /authors on mux (any goninja.Router —
// *http.ServeMux, or an adapter for gin/echo/chi), or under r's
// ResourceConfig.Path/Routes override (see resourceConfig above) if one is
// set. Every handler is wrapped through r.Protect, which applies this
// resource's Config (global default auth + generic middleware, set via
// API.MountWithConfig — see config.go) combined with cfg's own per-route
// Auth override (ResourceConfig.Auth, keyed by Route); a resource mounted
// via plain API.Mount has a zero Config, so Protect is a no-op there.
// Every Action declared via SetActions is mounted last, on the same mux,
// at <path>[/{id}][/UrlPath] depending on its Detail/UrlPath.
func (r *AuthorResource) Register(mux goninja.Router) {
	cfg := r.resourceConfig()
	path := cfg.PathOr("/authors")
	for _, rt := range [...]struct {
		route   goninja.Route
		method  string
		path    string
		handler http.HandlerFunc
	}{
		{goninja.RouteList, "GET", path, r.listHandler},
		{goninja.RouteCreate, "POST", path, r.createHandler},
		{goninja.RouteRetrieve, "GET", path + "/{id}", r.retrieveHandler},
		{goninja.RouteUpdate, "PUT", path + "/{id}", r.updateHandler},
		{goninja.RouteDelete, "DELETE", path + "/{id}", r.deleteHandler},
	} {
		if cfg.RouteEnabled(rt.route) {
			mux.HandleFunc(rt.method+" "+rt.path, r.Protect(rt.route, cfg, rt.handler))
		}
	}
	for _, a := range r.Actions() {
		p := path
		if a.Detail {
			p += "/{id}"
		}
		if a.UrlPath != "" {
			p += "/" + a.UrlPath
		}
		mux.HandleFunc(a.Method+" "+p, r.Protect(goninja.Route(a.Name), cfg, a.Handler))
	}
}
