// Code generated by goninja generate. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"

	"github.com/caspel26/goninja"
	"gorm.io/gorm"

	"github.com/caspel26/goninja/examples/prototype/models"
)

// AuthorListSchema is the shape returned by GET /authors.
type AuthorListSchema struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// AuthorRetrieveSchema is the shape returned by GET /authors/{id}.
// A relation field (e.g. Author) is nested as that model's own
// RetrieveSchema, never the raw related struct — output schemas are
// always separate from the model, so a sensitive field can't leak into a
// response just because it exists on the related struct either.
type AuthorRetrieveSchema struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Bio  string `json:"bio"`
}

// AuthorCreateSchema is the shape accepted by POST /authors.
// `validate` tags (go-playground/validator syntax) are copied verbatim from
// the model field's own `validate` tag, and enforced by goninja.Validate
// before Create runs.
type AuthorCreateSchema struct {
	Name string `json:"name" validate:"required,max=120"`
	Bio  string `json:"bio" validate:"max=2000"`
}

// AuthorUpdateSchema is the shape accepted by PUT /authors/{id}.
type AuthorUpdateSchema struct {
	Name string `json:"name" validate:"required,max=120"`
	Bio  string `json:"bio" validate:"max=2000"`
}

func toAuthorListSchema(m *models.Author) AuthorListSchema {
	return AuthorListSchema{
		ID:   m.ID,
		Name: m.Name,
	}
}

func toAuthorRetrieveSchema(m *models.Author) AuthorRetrieveSchema {
	return AuthorRetrieveSchema{
		ID:   m.ID,
		Name: m.Name,
		Bio:  m.Bio,
	}
}

// AuthorResource is the generated GORM-backed CRUD resource for
// Author. Embeds goninja.BaseResource for a transaction-aware
// DB(ctx) and a configurable ErrorMapper.
type AuthorResource struct {
	goninja.BaseResource
}

// NewAuthorResource builds a AuthorResource bound to db.
func NewAuthorResource(db *gorm.DB) *AuthorResource {
	r := &AuthorResource{}
	r.SetDB(db)
	return r
}

func (r *AuthorResource) List(ctx context.Context) ([]AuthorListSchema, error) {
	var items []models.Author
	if err := r.DB(ctx).Find(&items).Error; err != nil {
		return nil, err
	}
	out := make([]AuthorListSchema, 0, len(items))
	for i := range items {
		out = append(out, toAuthorListSchema(&items[i]))
	}
	return out, nil
}

// Retrieve preloads every relation field carried on the retrieve schema —
// list never does, by construction, which is why list/retrieve are
// separate tags (plan section 5.5): it's the guarantee against N+1, not an
// implementation detail.
func (r *AuthorResource) Retrieve(ctx context.Context, id int64) (*AuthorRetrieveSchema, error) {
	q := r.DB(ctx)

	var m models.Author
	if err := q.First(&m, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "author", ID: id}
		}
		return nil, err
	}
	out := toAuthorRetrieveSchema(&m)
	return &out, nil
}

func (r *AuthorResource) Create(ctx context.Context, in AuthorCreateSchema) (*AuthorRetrieveSchema, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	m := models.Author{
		Name: in.Name,
		Bio:  in.Bio,
	}
	if err := r.DB(ctx).Create(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, m.ID)
}

func (r *AuthorResource) Update(ctx context.Context, id int64, in AuthorUpdateSchema) (*AuthorRetrieveSchema, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	var m models.Author
	if err := r.DB(ctx).First(&m, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "author", ID: id}
		}
		return nil, err
	}
	m.Name = in.Name
	m.Bio = in.Bio
	if err := r.DB(ctx).Save(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, id)
}

func (r *AuthorResource) Delete(ctx context.Context, id int64) error {
	res := r.DB(ctx).Delete(&models.Author{}, id)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return goninja.NotFound{Resource: "author", ID: id}
	}
	return nil
}

func (r *AuthorResource) listHandler(w http.ResponseWriter, req *http.Request) {
	items, err := r.List(req.Context())
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, items)
}

func (r *AuthorResource) retrieveHandler(w http.ResponseWriter, req *http.Request) {
	id, err := strconv.ParseInt(req.PathValue("id"), 10, 64)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}
	out, err := r.Retrieve(req.Context(), id)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

func (r *AuthorResource) createHandler(w http.ResponseWriter, req *http.Request) {
	var in AuthorCreateSchema
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	out, err := r.Create(req.Context(), in)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusCreated, out)
}

func (r *AuthorResource) updateHandler(w http.ResponseWriter, req *http.Request) {
	id, err := strconv.ParseInt(req.PathValue("id"), 10, 64)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}
	var in AuthorUpdateSchema
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	out, err := r.Update(req.Context(), id, in)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

func (r *AuthorResource) deleteHandler(w http.ResponseWriter, req *http.Request) {
	id, err := strconv.ParseInt(req.PathValue("id"), 10, 64)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}
	if err := r.Delete(req.Context(), id); err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// Register mounts list/retrieve/create/update/delete routes for
// Author under /authors on mux.
func (r *AuthorResource) Register(mux *http.ServeMux) {
	mux.HandleFunc("GET /authors", r.listHandler)
	mux.HandleFunc("POST /authors", r.createHandler)
	mux.HandleFunc("GET /authors/{id}", r.retrieveHandler)
	mux.HandleFunc("PUT /authors/{id}", r.updateHandler)
	mux.HandleFunc("DELETE /authors/{id}", r.deleteHandler)
}
