// Code generated by goninja generate. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/caspel26/goninja"
	"github.com/caspel26/goninja/id"
	"github.com/caspel26/goninja/openapi"
	"gorm.io/gorm"

	"github.com/caspel26/goninja/examples/prototype/models"
)

// BookList is the shape returned by GET /books,
// one item per row of the "items" field of goninja.ListEnvelope.
type BookList struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	AuthorID  string    `json:"author_id"`
	Price     float64   `json:"price"`
	Published bool      `json:"published"`
	CreatedAt time.Time `json:"created_at"`
}

// BookRetrieve is the shape returned by GET /books/{id}.
// A relation field (e.g. Author) is nested as that model's own Retrieve
// type, never the raw related struct — output types are always separate
// from the model, so a sensitive field can't leak into a response just
// because it exists on the related struct either. A relation field tagged
// "byid" instead exposes only the related model's ID,
// as "<field>_id" — no nesting, no Preload.
type BookRetrieve struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	AuthorID  string         `json:"author_id"`
	Author    AuthorRetrieve `json:"author"`
	Price     float64        `json:"price"`
	Published bool           `json:"published"`
	CreatedAt time.Time      `json:"created_at"`
}

// BookCreate is the shape accepted by POST /books.
// `validate` tags (go-playground/validator syntax) are copied verbatim from
// the model field's own `validate` tag, and enforced by goninja.Validate
// before Create runs.
type BookCreate struct {
	Title     string  `json:"title" validate:"required,max=200"`
	AuthorID  string  `json:"author_id" validate:"required,uuid4"`
	Price     float64 `json:"price" validate:"min=0"`
	Published bool    `json:"published"`
}

// BookUpdate is the shape accepted by PUT /books/{id}.
type BookUpdate struct {
	Title     string  `json:"title" validate:"required,max=200"`
	AuthorID  string  `json:"author_id" validate:"required,uuid4"`
	Price     float64 `json:"price" validate:"min=0"`
	Published bool    `json:"published"`
}

// BookFilters is the shape parsed from GET /books
// query parameters: one exact-match pointer field
// per `filter`-tagged model field, plus Min/Max range pointers for numeric
// ones, plus Limit/Offset/Order shared by every model's list query. A nil
// field means "no filter" — List only adds a WHERE clause for the ones the
// caller actually set.
type BookFilters struct {
	AuthorID  *string
	Price     *float64
	PriceMin  *float64
	PriceMax  *float64
	Published *bool
	CreatedAt *time.Time
	Limit     int
	Offset    int
	// Order is a list-field JSON name, optionally "-"-prefixed for
	// descending (e.g. "-created_at"). Unknown field names are ignored.
	Order string
}

// bookOrderableColumns whitelists which query values
// "order" accepts — every list field, keyed by its JSON name and valued by
// its GORM database column. Only ever indexed with a known key, never
// interpolated from user input directly, so this doubles as the
// SQL-injection guard for ORDER BY.
// bookListColumns are the columns List reads — one per
// `list` field. Without this the query would SELECT *, loading columns
// BookList doesn't carry just to discard them after scanning.
var bookListColumns = []string{
	"id",
	"title",
	"author_id",
	"price",
	"published",
	"created_at",
}

var bookOrderableColumns = map[string]string{
	"id":         "id",
	"title":      "title",
	"author_id":  "author_id",
	"price":      "price",
	"published":  "published",
	"created_at": "created_at",
}

// bookInvalidIDMsg/bookIDQuery/
// bookContentTypeJSON/bookNotFoundDesc/
// bookRetrieveRef are shared across this file's
// handlers/resource methods (including OpenAPI() and its helpers below) to
// avoid repeating the same literal per call site — package-level, prefixed
// per model since several models can be generated into the same output
// package.
const (
	bookInvalidIDMsg    = "invalid id"
	bookIDQuery         = "id = ?"
	bookContentTypeJSON = "application/json"
	bookNotFoundDesc    = "Not found"
	bookRetrieveRef     = "#/components/schemas/BookRetrieve"
)

func toBookList(m *models.Book) BookList {
	return BookList{
		ID:        m.ID,
		Title:     m.Title,
		AuthorID:  m.AuthorID,
		Price:     m.Price,
		Published: m.Published,
		CreatedAt: m.CreatedAt,
	}
}

func toBookRetrieve(m *models.Book) BookRetrieve {
	return BookRetrieve{
		ID:        m.ID,
		Title:     m.Title,
		AuthorID:  m.AuthorID,
		Author:    toAuthorRetrieve(&m.Author),
		Price:     m.Price,
		Published: m.Published,
		CreatedAt: m.CreatedAt,
	}
}

// BookResource is the generated GORM-backed CRUD resource for
// Book. Embeds goninja.BaseResource for a transaction-aware
// DB(ctx) and a configurable ErrorMapper.
type BookResource struct {
	goninja.BaseResource
}

// BookOption configures a BookResource at
// construction time — see NewBookResource. Build one with
// goninja.Actions to attach custom Actions right at construction, e.g.
// NewBookResource(db, goninja.Actions(build, arg)).
type BookOption func(*BookResource)

// NewBookResource builds a BookResource bound to db,
// applying opts in order — see BookOption. Safe to call with no
// opts at all; existing callers that never pass any keep working
// unchanged.
func NewBookResource(db *gorm.DB, opts ...BookOption) *BookResource {
	r := &BookResource{}
	r.SetDB(db)
	r.SetSelf(r)
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// BookOps is the method set the generated handlers dispatch
// every request through. A type embedding BookResource and
// overriding one of these methods is picked up
// automatically once wired in via SetSelf — see ops() below.
type BookOps interface {
	List(ctx context.Context, f BookFilters) ([]BookList, int64, error)
	Retrieve(ctx context.Context, id string) (*BookRetrieve, error)
	Create(ctx context.Context, in BookCreate) (*BookRetrieve, error)
	Update(ctx context.Context, id string, in BookUpdate) (*BookRetrieve, error)
	Delete(ctx context.Context, id string) error
}

// ops returns the BookOps the generated handlers should call:
// r.Self() if it satisfies the interface (a wrapper type overriding one or
// more methods), otherwise r itself. r.Self() is r by default (set by
// NewBookResource), so this is a no-op unless SetSelf was
// called again with a different value.
func (r *BookResource) ops() BookOps {
	if o, ok := r.Self().(BookOps); ok {
		return o
	}
	return r
}

// List applies f's filters/ordering, counts the total matching rows before
// paginating, and returns Limit/Offset rows plus that total — never a
// Preload, by construction, which is why list/retrieve are separate tags:
// it's the guarantee against N+1, not an implementation detail.
func (r *BookResource) List(ctx context.Context, f BookFilters) ([]BookList, int64, error) {
	q := r.DB(ctx).Model(&models.Book{})
	if f.AuthorID != nil {
		q = q.Where("author_id = ?", *f.AuthorID)
	}
	if f.Price != nil {
		q = q.Where("price = ?", *f.Price)
	}
	if f.PriceMin != nil {
		q = q.Where("price >= ?", *f.PriceMin)
	}
	if f.PriceMax != nil {
		q = q.Where("price <= ?", *f.PriceMax)
	}
	if f.Published != nil {
		q = q.Where("published = ?", *f.Published)
	}
	if f.CreatedAt != nil {
		q = q.Where("created_at = ?", *f.CreatedAt)
	}

	var total int64
	if err := q.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	if f.Order != "" {
		field, desc := strings.CutPrefix(f.Order, "-")
		if col, ok := bookOrderableColumns[field]; ok {
			dir := "ASC"
			if desc {
				dir = "DESC"
			}
			q = q.Order(col + " " + dir)
		}
	}

	var items []models.Book
	if err := q.Select(bookListColumns).Limit(f.Limit).Offset(f.Offset).Find(&items).Error; err != nil {
		return nil, 0, err
	}
	out := make([]BookList, 0, len(items))
	for i := range items {
		out = append(out, toBookList(&items[i]))
	}
	return out, total, nil
}

// Retrieve preloads every relation field carried on the retrieve type —
// list never does, by construction (see List above) — except one tagged
// "byid", which exposes only the related ID and so
// skips the Preload entirely.
func (r *BookResource) Retrieve(ctx context.Context, id string) (*BookRetrieve, error) {
	q := r.DB(ctx)
	q = q.Preload("Author")

	var m models.Book
	if err := q.First(&m, bookIDQuery, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "book", ID: id}
		}
		return nil, err
	}
	out := toBookRetrieve(&m)
	return &out, nil
}

func (r *BookResource) Create(ctx context.Context, in BookCreate) (*BookRetrieve, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	m := models.Book{
		Title:     in.Title,
		AuthorID:  in.AuthorID,
		Price:     in.Price,
		Published: in.Published,
	}
	if m.ID == "" {
		m.ID = id.NewUUID()
	}
	if err := r.DB(ctx).Create(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, m.ID)
}

func (r *BookResource) Update(ctx context.Context, id string, in BookUpdate) (*BookRetrieve, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	var m models.Book
	if err := r.DB(ctx).First(&m, bookIDQuery, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "book", ID: id}
		}
		return nil, err
	}
	m.Title = in.Title
	m.AuthorID = in.AuthorID
	m.Price = in.Price
	m.Published = in.Published
	if err := r.DB(ctx).Save(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, id)
}

func (r *BookResource) Delete(ctx context.Context, id string) error {
	res := r.DB(ctx).Where(bookIDQuery, id).Delete(&models.Book{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return goninja.NotFound{Resource: "book", ID: id}
	}
	return nil
}

// parseBookFilters reads BookFilters from the request's
// query parameters, keyed by each field's JSON name (plus "_min"/"_max" for
// numeric range filters). A value that fails to parse is a BadRequest.
func parseBookFilters(req *http.Request) (BookFilters, error) {
	q := req.URL.Query()
	var f BookFilters

	if v := q.Get("author_id"); v != "" {
		parsed := v
		f.AuthorID = &parsed
	}

	if v := q.Get("price"); v != "" {
		n, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return f, goninja.BadRequest{Detail: "invalid price"}
		}
		parsed := float64(n)
		f.Price = &parsed
	}
	if v := q.Get("price_min"); v != "" {
		n, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return f, goninja.BadRequest{Detail: "invalid price_min"}
		}
		parsed := float64(n)
		f.PriceMin = &parsed
	}
	if v := q.Get("price_max"); v != "" {
		n, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return f, goninja.BadRequest{Detail: "invalid price_max"}
		}
		parsed := float64(n)
		f.PriceMax = &parsed
	}

	if v := q.Get("published"); v != "" {
		parsed, err := strconv.ParseBool(v)
		if err != nil {
			return f, goninja.BadRequest{Detail: "invalid published"}
		}
		f.Published = &parsed
	}

	if v := q.Get("created_at"); v != "" {
		parsed, err := time.Parse(time.RFC3339, v)
		if err != nil {
			return f, goninja.BadRequest{Detail: "invalid created_at"}
		}
		f.CreatedAt = &parsed
	}

	limit, offset, err := goninja.ParseLimitOffset(q)
	if err != nil {
		return f, err
	}
	f.Limit = limit
	f.Offset = offset

	// Reject an unknown order field here rather than ignoring it in List: a
	// typo would otherwise return the default order with a 200, which reads
	// as "sorted the way you asked" and is impossible to notice from the
	// response.
	if order := q.Get("order"); order != "" {
		field, _ := strings.CutPrefix(order, "-")
		if _, ok := bookOrderableColumns[field]; !ok {
			return f, goninja.BadRequest{
				Detail: "cannot order by \"" + field + "\"",
				Code:   "INVALID_ORDER_FIELD",
			}
		}
		f.Order = order
	}

	return f, nil
}

func (r *BookResource) listHandler(w http.ResponseWriter, req *http.Request) {
	f, err := parseBookFilters(req)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	items, total, err := r.ops().List(req.Context(), f)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, goninja.ListEnvelope[BookList]{
		Items:  items,
		Total:  total,
		Limit:  f.Limit,
		Offset: f.Offset,
	})
}

func (r *BookResource) retrieveHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: bookInvalidIDMsg})
		return
	}

	out, err := r.ops().Retrieve(req.Context(), id)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// createHandler runs BeforeCreateHook/AfterCreateHook (hooks.go), if r's
// Self() implements them, in the same transaction as the create itself —
// a hook returning an error rolls the whole request back.
func (r *BookResource) createHandler(w http.ResponseWriter, req *http.Request) {
	var in BookCreate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*BookRetrieve, error) {
		if h, ok := self.(goninja.BeforeCreateHook[BookCreate]); ok {
			if err := h.BeforeCreate(ctx, &in); err != nil {
				return nil, err
			}
		}
		created, err := ops.Create(ctx, in)
		if err != nil {
			return nil, err
		}
		if h, ok := self.(goninja.AfterCreateHook[BookRetrieve]); ok {
			if err := h.AfterCreate(ctx, created); err != nil {
				return nil, err
			}
		}
		return created, nil
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusCreated, out)
}

// updateHandler runs BeforeUpdateHook (hooks.go), if r's Self() implements
// it, in the same transaction as the update itself.
func (r *BookResource) updateHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: bookInvalidIDMsg})
		return
	}

	var in BookUpdate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*BookRetrieve, error) {
		if h, ok := self.(goninja.BeforeUpdateHook[BookUpdate]); ok {
			if err := h.BeforeUpdate(ctx, &in); err != nil {
				return nil, err
			}
		}
		return ops.Update(ctx, id, in)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// deleteHandler runs BeforeDeleteHook (hooks.go), if r's Self() implements
// it, in the same transaction as the delete itself.
func (r *BookResource) deleteHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: bookInvalidIDMsg})
		return
	}

	self, ops := r.Self(), r.ops()
	_, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (struct{}, error) {
		if h, ok := self.(goninja.BeforeDeleteHook[string]); ok {
			if err := h.BeforeDelete(ctx, id); err != nil {
				return struct{}{}, err
			}
		}
		return struct{}{}, ops.Delete(ctx, id)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// OpenAPI returns this resource's fragment of a merged OpenAPI document —
// the paths it mounts, the schemas those paths reference, and the security
// schemes any protected path's Security refers to (resolved via
// r.SecurityFor, the same logic Register's r.Protect calls enforce, so the
// two can't drift apart) — built from the same IR as the rest of this
// file, so they always match what List/Retrieve/Create/Update actually
// accept and return. Pass this resource to a goninja.API's Add method
// (alongside its Register(mux) call) to merge it in, or just pass it to
// API.Mount; see API.MountDocs.
func (r *BookResource) OpenAPI() (map[string]*openapi.PathItem, map[string]openapi.Schema, map[string]openapi.SecurityScheme) {
	schemas := map[string]openapi.Schema{
		"BookList": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"id":         {Type: "string"},
				"title":      {Type: "string"},
				"author_id":  {Type: "string"},
				"price":      {Type: "number", Format: "double"},
				"published":  {Type: "boolean"},
				"created_at": {Type: "string", Format: "date-time"},
			},
		},
		"BookRetrieve": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"id":         {Type: "string"},
				"title":      {Type: "string"},
				"author_id":  {Type: "string"},
				"author":     {Ref: "#/components/schemas/AuthorRetrieve"},
				"price":      {Type: "number", Format: "double"},
				"published":  {Type: "boolean"},
				"created_at": {Type: "string", Format: "date-time"},
			},
		},
		"BookCreate": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"title":     {Type: "string"},
				"author_id": {Type: "string"},
				"price":     {Type: "number", Format: "double"},
				"published": {Type: "boolean"},
			},
			Required: []string{"title", "author_id"},
		},
		"BookUpdate": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"title":     {Type: "string"},
				"author_id": {Type: "string"},
				"price":     {Type: "number", Format: "double"},
				"published": {Type: "boolean"},
			},
			Required: []string{"title", "author_id"},
		},
	}

	listParams := []openapi.Parameter{
		{Name: "author_id", In: "query", Schema: openapi.Schema{Type: "string"}},
		{Name: "price", In: "query", Schema: openapi.Schema{Type: "number", Format: "double"}},
		{Name: "price_min", In: "query", Schema: openapi.Schema{Type: "number", Format: "double"}},
		{Name: "price_max", In: "query", Schema: openapi.Schema{Type: "number", Format: "double"}},
		{Name: "published", In: "query", Schema: openapi.Schema{Type: "boolean"}},
		{Name: "created_at", In: "query", Schema: openapi.Schema{Type: "string", Format: "date-time"}},
	}

	return goninja.BuildResourceOpenAPI(&r.BaseResource, r.resourceConfig(), goninja.ResourceDoc{
		Name:      "Book",
		NameLower: "book",
		IDSchema: openapi.Schema{
			Type: "string",
		},
		Schemas:    schemas,
		ListParams: listParams,
	})
}

// resourceConfig resolves r's ResourceConfig via r.Self(), the same
// dispatch hooks.go and ops() use: a wrapper implementing
// goninja.Configurer customizes it, otherwise every
// generated default applies.
func (r *BookResource) resourceConfig() goninja.ResourceConfig {
	if c, ok := r.Self().(goninja.Configurer); ok {
		return c.Config()
	}
	return goninja.ResourceConfig{}
}

// Register mounts list/retrieve/create/update/delete routes for
// Book under /books on mux (any goninja.Router —
// *http.ServeMux, or an adapter for gin/echo/chi), or under r's
// ResourceConfig.Path/Routes override (see resourceConfig above) if one is
// set. Every handler is wrapped through r.Protect, which applies this
// resource's Config (global default auth + generic middleware, set via
// API.MountWithConfig — see config.go) combined with cfg's own per-route
// Auth override (ResourceConfig.Auth, keyed by Route); a resource mounted
// via plain API.Mount has a zero Config, so Protect is a no-op there.
// Every Action declared via SetActions is mounted last, on the same mux,
// at <path>[/{id}][/UrlPath] depending on its Detail/UrlPath, wrapped
// through r.ProtectAction instead (consults Action.Auth first). Before
// mounting anything, r.CheckStrictAuth panics if Config.StrictAuth is set
// and any route below has no explicit auth decision — a no-op otherwise.
func (r *BookResource) Register(mux goninja.Router) {
	cfg := r.resourceConfig()
	path := cfg.PathOr("/books")
	crudRoutes := [...]struct {
		route   goninja.Route
		method  string
		path    string
		handler http.HandlerFunc
	}{
		{goninja.RouteList, "GET", path, r.listHandler},
		{goninja.RouteCreate, "POST", path, r.createHandler},
		{goninja.RouteRetrieve, "GET", path + "/{id}", r.retrieveHandler},
		{goninja.RouteUpdate, "PUT", path + "/{id}", r.updateHandler},
		{goninja.RouteDelete, "DELETE", path + "/{id}", r.deleteHandler},
	}
	var enabledRoutes []goninja.Route
	for _, rt := range crudRoutes {
		if cfg.RouteEnabled(rt.route) {
			enabledRoutes = append(enabledRoutes, rt.route)
		}
	}
	r.CheckStrictAuth(enabledRoutes, r.Actions(), cfg)
	for _, rt := range crudRoutes {
		if cfg.RouteEnabled(rt.route) {
			mux.HandleFunc(rt.method+" "+rt.path, r.Protect(rt.route, cfg, rt.handler))
		}
	}
	for _, a := range r.Actions() {
		p := path
		if a.Detail {
			p += "/{id}"
		}
		if a.UrlPath != "" {
			p += "/" + a.UrlPath
		}
		mux.HandleFunc(a.Method+" "+p, r.ProtectAction(a, cfg))
	}
}
