// Code generated by goninja generate. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"

	"github.com/caspel26/goninja"
	"gorm.io/gorm"

	"github.com/caspel26/goninja/examples/prototype/models"
)

// BookListSchema is the shape returned by GET /books.
type BookListSchema struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	AuthorID int64  `json:"author_id"`
}

// BookRetrieveSchema is the shape returned by GET /books/{id}.
// A relation field (e.g. Author) is nested as that model's own
// RetrieveSchema, never the raw related struct — output schemas are
// always separate from the model, so a sensitive field can't leak into a
// response just because it exists on the related struct either.
type BookRetrieveSchema struct {
	ID       int64                `json:"id"`
	Title    string               `json:"title"`
	AuthorID int64                `json:"author_id"`
	Author   AuthorRetrieveSchema `json:"author"`
}

// BookCreateSchema is the shape accepted by POST /books.
type BookCreateSchema struct {
	Title    string `json:"title"`
	AuthorID int64  `json:"author_id"`
}

// BookUpdateSchema is the shape accepted by PUT /books/{id}.
type BookUpdateSchema struct {
	Title    string `json:"title"`
	AuthorID int64  `json:"author_id"`
}

func toBookListSchema(m *models.Book) BookListSchema {
	return BookListSchema{
		ID:       m.ID,
		Title:    m.Title,
		AuthorID: m.AuthorID,
	}
}

func toBookRetrieveSchema(m *models.Book) BookRetrieveSchema {
	return BookRetrieveSchema{
		ID:       m.ID,
		Title:    m.Title,
		AuthorID: m.AuthorID,
		Author:   toAuthorRetrieveSchema(&m.Author),
	}
}

// BookResource is the generated GORM-backed CRUD resource for
// Book. Embeds goninja.BaseResource for a transaction-aware
// DB(ctx).
type BookResource struct {
	goninja.BaseResource
}

// NewBookResource builds a BookResource bound to db.
func NewBookResource(db *gorm.DB) *BookResource {
	r := &BookResource{}
	r.SetDB(db)
	return r
}

func (r *BookResource) List(ctx context.Context) ([]BookListSchema, error) {
	var items []models.Book
	if err := r.DB(ctx).Find(&items).Error; err != nil {
		return nil, err
	}
	out := make([]BookListSchema, 0, len(items))
	for i := range items {
		out = append(out, toBookListSchema(&items[i]))
	}
	return out, nil
}

// Retrieve preloads every relation field carried on the retrieve schema —
// list never does, by construction, which is why list/retrieve are
// separate tags (plan section 5.5): it's the guarantee against N+1, not an
// implementation detail.
func (r *BookResource) Retrieve(ctx context.Context, id int64) (*BookRetrieveSchema, error) {
	q := r.DB(ctx)
	q = q.Preload("Author")

	var m models.Book
	if err := q.First(&m, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "book", ID: id}
		}
		return nil, err
	}
	out := toBookRetrieveSchema(&m)
	return &out, nil
}

func (r *BookResource) Create(ctx context.Context, in BookCreateSchema) (*BookRetrieveSchema, error) {
	m := models.Book{
		Title:    in.Title,
		AuthorID: in.AuthorID,
	}
	if err := r.DB(ctx).Create(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, m.ID)
}

func (r *BookResource) Update(ctx context.Context, id int64, in BookUpdateSchema) (*BookRetrieveSchema, error) {
	var m models.Book
	if err := r.DB(ctx).First(&m, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "book", ID: id}
		}
		return nil, err
	}
	m.Title = in.Title
	m.AuthorID = in.AuthorID
	if err := r.DB(ctx).Save(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, id)
}

func (r *BookResource) Delete(ctx context.Context, id int64) error {
	res := r.DB(ctx).Delete(&models.Book{}, id)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return goninja.NotFound{Resource: "book", ID: id}
	}
	return nil
}

func (r *BookResource) listHandler(w http.ResponseWriter, req *http.Request) {
	items, err := r.List(req.Context())
	if err != nil {
		mapError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, items)
}

func (r *BookResource) retrieveHandler(w http.ResponseWriter, req *http.Request) {
	id, err := idFromPath(req.URL.Path)
	if err != nil {
		http.Error(w, "invalid id", http.StatusBadRequest)
		return
	}
	out, err := r.Retrieve(req.Context(), id)
	if err != nil {
		mapError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, out)
}

func (r *BookResource) createHandler(w http.ResponseWriter, req *http.Request) {
	var in BookCreateSchema
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		http.Error(w, "invalid json", http.StatusBadRequest)
		return
	}
	out, err := r.Create(req.Context(), in)
	if err != nil {
		mapError(w, err)
		return
	}
	writeJSON(w, http.StatusCreated, out)
}

func (r *BookResource) updateHandler(w http.ResponseWriter, req *http.Request) {
	id, err := idFromPath(req.URL.Path)
	if err != nil {
		http.Error(w, "invalid id", http.StatusBadRequest)
		return
	}
	var in BookUpdateSchema
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		http.Error(w, "invalid json", http.StatusBadRequest)
		return
	}
	out, err := r.Update(req.Context(), id, in)
	if err != nil {
		mapError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, out)
}

func (r *BookResource) deleteHandler(w http.ResponseWriter, req *http.Request) {
	id, err := idFromPath(req.URL.Path)
	if err != nil {
		http.Error(w, "invalid id", http.StatusBadRequest)
		return
	}
	if err := r.Delete(req.Context(), id); err != nil {
		mapError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// Register mounts list/retrieve/create/update/delete routes for
// Book under /books on mux.
func (r *BookResource) Register(mux *http.ServeMux) {
	mux.HandleFunc("GET /books", r.listHandler)
	mux.HandleFunc("POST /books", r.createHandler)
	mux.HandleFunc("GET /books/{id}", r.retrieveHandler)
	mux.HandleFunc("PUT /books/{id}", r.updateHandler)
	mux.HandleFunc("DELETE /books/{id}", r.deleteHandler)
}
