// Code generated by goninja generate. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/caspel26/goninja"
	"gorm.io/gorm"

	"github.com/caspel26/goninja/examples/prototype/models"
)

// TaskList is the shape returned by GET /tasks,
// one item per row of the "items" field of goninja.ListEnvelope.
type TaskList struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}

// TaskRetrieve is the shape returned by GET /tasks/{id}.
// A relation field (e.g. Author) is nested as that model's own
// Retrieve type, never the raw related struct — output types are
// always separate from the model, so a sensitive field can't leak into a
// response just because it exists on the related struct either.
type TaskRetrieve struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}

// TaskCreate is the shape accepted by POST /tasks.
// `validate` tags (go-playground/validator syntax) are copied verbatim from
// the model field's own `validate` tag, and enforced by goninja.Validate
// before Create runs.
type TaskCreate struct {
	Title string `json:"title" validate:"required,max=200"`
	Done  bool   `json:"done"`
}

// TaskUpdate is the shape accepted by PUT /tasks/{id}.
type TaskUpdate struct {
	Title string `json:"title" validate:"required,max=200"`
	Done  bool   `json:"done"`
}

// TaskFilters is the shape parsed from GET /tasks
// query parameters (plan section 5.5/Fase 4): one exact-match pointer field
// per `filter`-tagged model field, plus Min/Max range pointers for numeric
// ones, plus Limit/Offset/Order shared by every model's list query. A nil
// field means "no filter" — List only adds a WHERE clause for the ones the
// caller actually set.
type TaskFilters struct {
	Done   *bool
	Limit  int
	Offset int
	// Order is a list-field JSON name, optionally "-"-prefixed for
	// descending (e.g. "-created_at"). Unknown field names are ignored.
	Order string
}

// taskOrderableColumns whitelists which query values
// "order" accepts — every list field, keyed and valued by its JSON name
// (assumed to match the actual DB column, per this model's `json` tags).
// Only ever indexed with a known key, never interpolated from user input
// directly, so this doubles as the SQL-injection guard for ORDER BY.
var taskOrderableColumns = map[string]string{
	"id":    "id",
	"title": "title",
	"done":  "done",
}

func toTaskList(m *models.Task) TaskList {
	return TaskList{
		ID:    m.ID,
		Title: m.Title,
		Done:  m.Done,
	}
}

func toTaskRetrieve(m *models.Task) TaskRetrieve {
	return TaskRetrieve{
		ID:    m.ID,
		Title: m.Title,
		Done:  m.Done,
	}
}

// TaskResource is the generated GORM-backed CRUD resource for
// Task. Embeds goninja.BaseResource for a transaction-aware
// DB(ctx) and a configurable ErrorMapper.
type TaskResource struct {
	goninja.BaseResource
}

// NewTaskResource builds a TaskResource bound to db.
func NewTaskResource(db *gorm.DB) *TaskResource {
	r := &TaskResource{}
	r.SetDB(db)
	r.SetSelf(r)
	return r
}

// TaskOps is the method set the generated handlers dispatch
// every request through. A type embedding TaskResource and
// overriding one of these methods (plan section 5.10) is picked up
// automatically once wired in via SetSelf — see ops() below.
type TaskOps interface {
	List(ctx context.Context, f TaskFilters) ([]TaskList, int64, error)
	Retrieve(ctx context.Context, id string) (*TaskRetrieve, error)
	Create(ctx context.Context, in TaskCreate) (*TaskRetrieve, error)
	Update(ctx context.Context, id string, in TaskUpdate) (*TaskRetrieve, error)
	Delete(ctx context.Context, id string) error
}

// ops returns the TaskOps the generated handlers should call:
// r.Self() if it satisfies the interface (a wrapper type overriding one or
// more methods), otherwise r itself. r.Self() is r by default (set by
// NewTaskResource), so this is a no-op unless SetSelf was
// called again with a different value.
func (r *TaskResource) ops() TaskOps {
	if o, ok := r.Self().(TaskOps); ok {
		return o
	}
	return r
}

// List applies f's filters/ordering, counts the total matching rows before
// paginating, and returns Limit/Offset rows plus that total — never a
// Preload, by construction, which is why list/retrieve are separate tags
// (plan section 5.5): it's the guarantee against N+1, not an
// implementation detail.
func (r *TaskResource) List(ctx context.Context, f TaskFilters) ([]TaskList, int64, error) {
	q := r.DB(ctx).Model(&models.Task{})
	if f.Done != nil {
		q = q.Where("done = ?", *f.Done)
	}

	var total int64
	if err := q.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	if f.Order != "" {
		field, desc := strings.CutPrefix(f.Order, "-")
		if col, ok := taskOrderableColumns[field]; ok {
			dir := "ASC"
			if desc {
				dir = "DESC"
			}
			q = q.Order(col + " " + dir)
		}
	}

	var items []models.Task
	if err := q.Limit(f.Limit).Offset(f.Offset).Find(&items).Error; err != nil {
		return nil, 0, err
	}
	out := make([]TaskList, 0, len(items))
	for i := range items {
		out = append(out, toTaskList(&items[i]))
	}
	return out, total, nil
}

// Retrieve preloads every relation field carried on the retrieve type —
// list never does, by construction (see List above).
func (r *TaskResource) Retrieve(ctx context.Context, id string) (*TaskRetrieve, error) {
	q := r.DB(ctx)

	var m models.Task
	if err := q.First(&m, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "task", ID: id}
		}
		return nil, err
	}
	out := toTaskRetrieve(&m)
	return &out, nil
}

func (r *TaskResource) Create(ctx context.Context, in TaskCreate) (*TaskRetrieve, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	m := models.Task{
		Title: in.Title,
		Done:  in.Done,
	}
	if m.ID == "" {
		m.ID = goninja.NewUUID()
	}
	if err := r.DB(ctx).Create(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, m.ID)
}

func (r *TaskResource) Update(ctx context.Context, id string, in TaskUpdate) (*TaskRetrieve, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	var m models.Task
	if err := r.DB(ctx).First(&m, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "task", ID: id}
		}
		return nil, err
	}
	m.Title = in.Title
	m.Done = in.Done
	if err := r.DB(ctx).Save(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, id)
}

func (r *TaskResource) Delete(ctx context.Context, id string) error {
	res := r.DB(ctx).Where("id = ?", id).Delete(&models.Task{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return goninja.NotFound{Resource: "task", ID: id}
	}
	return nil
}

// parseTaskFilters reads TaskFilters from the request's
// query parameters, keyed by each field's JSON name (plus "_min"/"_max" for
// numeric range filters). A value that fails to parse is a BadRequest.
func parseTaskFilters(req *http.Request) (TaskFilters, error) {
	q := req.URL.Query()
	var f TaskFilters

	if v := q.Get("done"); v != "" {
		parsed, err := strconv.ParseBool(v)
		if err != nil {
			return f, goninja.BadRequest{Detail: "invalid done"}
		}
		f.Done = &parsed
	}

	limit, offset, err := goninja.ParseLimitOffset(q)
	if err != nil {
		return f, err
	}
	f.Limit = limit
	f.Offset = offset
	f.Order = q.Get("order")

	return f, nil
}

func (r *TaskResource) listHandler(w http.ResponseWriter, req *http.Request) {
	f, err := parseTaskFilters(req)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	items, total, err := r.ops().List(req.Context(), f)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, goninja.ListEnvelope[TaskList]{
		Items:  items,
		Total:  total,
		Limit:  f.Limit,
		Offset: f.Offset,
	})
}

func (r *TaskResource) retrieveHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}

	out, err := r.ops().Retrieve(req.Context(), id)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// createHandler runs BeforeCreateHook/AfterCreateHook (hooks.go), if r's
// Self() implements them, in the same transaction as the create itself —
// a hook returning an error rolls the whole request back (plan section
// 5.6/5.7).
func (r *TaskResource) createHandler(w http.ResponseWriter, req *http.Request) {
	var in TaskCreate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*TaskRetrieve, error) {
		if h, ok := self.(goninja.BeforeCreateHook[TaskCreate]); ok {
			if err := h.BeforeCreate(ctx, &in); err != nil {
				return nil, err
			}
		}
		created, err := ops.Create(ctx, in)
		if err != nil {
			return nil, err
		}
		if h, ok := self.(goninja.AfterCreateHook[TaskRetrieve]); ok {
			if err := h.AfterCreate(ctx, created); err != nil {
				return nil, err
			}
		}
		return created, nil
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusCreated, out)
}

// updateHandler runs BeforeUpdateHook (hooks.go), if r's Self() implements
// it, in the same transaction as the update itself.
func (r *TaskResource) updateHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}

	var in TaskUpdate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*TaskRetrieve, error) {
		if h, ok := self.(goninja.BeforeUpdateHook[TaskUpdate]); ok {
			if err := h.BeforeUpdate(ctx, &in); err != nil {
				return nil, err
			}
		}
		return ops.Update(ctx, id, in)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// deleteHandler runs BeforeDeleteHook (hooks.go), if r's Self() implements
// it, in the same transaction as the delete itself.
func (r *TaskResource) deleteHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}

	self, ops := r.Self(), r.ops()
	_, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (struct{}, error) {
		if h, ok := self.(goninja.BeforeDeleteHook[string]); ok {
			if err := h.BeforeDelete(ctx, id); err != nil {
				return struct{}{}, err
			}
		}
		return struct{}{}, ops.Delete(ctx, id)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// OpenAPI returns this resource's fragment of a merged OpenAPI document
// (plan section 5.10/Fase 5) — the paths it mounts and the schemas those
// paths reference, built from the same IR as the rest of this file, so
// they always match what List/Retrieve/Create/Update actually accept and
// return. Pass this resource to an goninja.API's Add method (alongside its
// Register(mux) call) to merge it in; see goninja.MountDocs.
func (r *TaskResource) OpenAPI() (map[string]*goninja.PathItem, map[string]goninja.Schema) {
	tags := r.OpenAPITags()
	if len(tags) == 0 {
		tags = []string{"Task"}
	}

	schemas := map[string]goninja.Schema{
		"TaskList": {
			Type: "object",
			Properties: map[string]goninja.Schema{
				"id":    {Type: "string"},
				"title": {Type: "string"},
				"done":  {Type: "boolean"},
			},
		},
		"TaskRetrieve": {
			Type: "object",
			Properties: map[string]goninja.Schema{
				"id":    {Type: "string"},
				"title": {Type: "string"},
				"done":  {Type: "boolean"},
			},
		},
		"TaskCreate": {
			Type: "object",
			Properties: map[string]goninja.Schema{
				"title": {Type: "string"},
				"done":  {Type: "boolean"},
			},
			Required: []string{"title"},
		},
		"TaskUpdate": {
			Type: "object",
			Properties: map[string]goninja.Schema{
				"title": {Type: "string"},
				"done":  {Type: "boolean"},
			},
			Required: []string{"title"},
		},
		"TaskListEnvelope": {
			Type: "object",
			Properties: map[string]goninja.Schema{
				"items":  {Type: "array", Items: &goninja.Schema{Ref: "#/components/schemas/TaskList"}},
				"total":  {Type: "integer", Format: "int64"},
				"limit":  {Type: "integer"},
				"offset": {Type: "integer"},
			},
		},
	}

	listParams := []goninja.Parameter{
		{Name: "done", In: "query", Schema: goninja.Schema{Type: "boolean"}},
		{Name: "limit", In: "query", Schema: goninja.Schema{Type: "integer"}},
		{Name: "offset", In: "query", Schema: goninja.Schema{Type: "integer"}},
		{Name: "order", In: "query", Schema: goninja.Schema{Type: "string"}},
	}

	idParam := goninja.Parameter{
		Name:     "id",
		In:       "path",
		Required: true,
		Schema:   goninja.Schema{Type: "string"},
	}

	paths := map[string]*goninja.PathItem{
		"/tasks": {
			Get: &goninja.Operation{
				Summary:    "List tasks",
				Tags:       tags,
				Parameters: listParams,
				Responses: map[string]goninja.Response{
					"200": {Description: "OK", Content: map[string]goninja.MediaType{
						"application/json": {Schema: goninja.Schema{Ref: "#/components/schemas/TaskListEnvelope"}},
					}},
				},
			},
			Post: &goninja.Operation{
				Summary: "Create a task",
				Tags:    tags,
				RequestBody: &goninja.RequestBody{
					Required: true,
					Content: map[string]goninja.MediaType{
						"application/json": {Schema: goninja.Schema{Ref: "#/components/schemas/TaskCreate"}},
					},
				},
				Responses: map[string]goninja.Response{
					"201": {Description: "Created", Content: map[string]goninja.MediaType{
						"application/json": {Schema: goninja.Schema{Ref: "#/components/schemas/TaskRetrieve"}},
					}},
					"422": {Description: "Validation error"},
				},
			},
		},
		"/tasks/{id}": {
			Get: &goninja.Operation{
				Summary:    "Retrieve a task",
				Tags:       tags,
				Parameters: []goninja.Parameter{idParam},
				Responses: map[string]goninja.Response{
					"200": {Description: "OK", Content: map[string]goninja.MediaType{
						"application/json": {Schema: goninja.Schema{Ref: "#/components/schemas/TaskRetrieve"}},
					}},
					"404": {Description: "Not found"},
				},
			},
			Put: &goninja.Operation{
				Summary:    "Update a task",
				Tags:       tags,
				Parameters: []goninja.Parameter{idParam},
				RequestBody: &goninja.RequestBody{
					Required: true,
					Content: map[string]goninja.MediaType{
						"application/json": {Schema: goninja.Schema{Ref: "#/components/schemas/TaskUpdate"}},
					},
				},
				Responses: map[string]goninja.Response{
					"200": {Description: "OK", Content: map[string]goninja.MediaType{
						"application/json": {Schema: goninja.Schema{Ref: "#/components/schemas/TaskRetrieve"}},
					}},
					"404": {Description: "Not found"},
					"422": {Description: "Validation error"},
				},
			},
			Delete: &goninja.Operation{
				Summary:    "Delete a task",
				Tags:       tags,
				Parameters: []goninja.Parameter{idParam},
				Responses: map[string]goninja.Response{
					"204": {Description: "No content"},
					"404": {Description: "Not found"},
				},
			},
		},
	}

	return paths, schemas
}

// Register mounts list/retrieve/create/update/delete routes for
// Task under /tasks on mux.
func (r *TaskResource) Register(mux *http.ServeMux) {
	mux.HandleFunc("GET /tasks", r.listHandler)
	mux.HandleFunc("POST /tasks", r.createHandler)
	mux.HandleFunc("GET /tasks/{id}", r.retrieveHandler)
	mux.HandleFunc("PUT /tasks/{id}", r.updateHandler)
	mux.HandleFunc("DELETE /tasks/{id}", r.deleteHandler)
}
