// Code generated by goninja generate. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"

	"github.com/caspel26/goninja"
	"gorm.io/gorm"

	"github.com/caspel26/goninja/examples/prototype/models"
)

// TaskListSchema is the shape returned by GET /tasks.
type TaskListSchema struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}

// TaskRetrieveSchema is the shape returned by GET /tasks/{id}.
// A relation field (e.g. Author) is nested as that model's own
// RetrieveSchema, never the raw related struct — output schemas are
// always separate from the model, so a sensitive field can't leak into a
// response just because it exists on the related struct either.
type TaskRetrieveSchema struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}

// TaskCreateSchema is the shape accepted by POST /tasks.
// `validate` tags (go-playground/validator syntax) are copied verbatim from
// the model field's own `validate` tag, and enforced by goninja.Validate
// before Create runs.
type TaskCreateSchema struct {
	Title string `json:"title" validate:"required,max=200"`
	Done  bool   `json:"done"`
}

// TaskUpdateSchema is the shape accepted by PUT /tasks/{id}.
type TaskUpdateSchema struct {
	Title string `json:"title" validate:"required,max=200"`
	Done  bool   `json:"done"`
}

func toTaskListSchema(m *models.Task) TaskListSchema {
	return TaskListSchema{
		ID:    m.ID,
		Title: m.Title,
		Done:  m.Done,
	}
}

func toTaskRetrieveSchema(m *models.Task) TaskRetrieveSchema {
	return TaskRetrieveSchema{
		ID:    m.ID,
		Title: m.Title,
		Done:  m.Done,
	}
}

// TaskResource is the generated GORM-backed CRUD resource for
// Task. Embeds goninja.BaseResource for a transaction-aware
// DB(ctx) and a configurable ErrorMapper.
type TaskResource struct {
	goninja.BaseResource
}

// NewTaskResource builds a TaskResource bound to db.
func NewTaskResource(db *gorm.DB) *TaskResource {
	r := &TaskResource{}
	r.SetDB(db)
	return r
}

func (r *TaskResource) List(ctx context.Context) ([]TaskListSchema, error) {
	var items []models.Task
	if err := r.DB(ctx).Find(&items).Error; err != nil {
		return nil, err
	}
	out := make([]TaskListSchema, 0, len(items))
	for i := range items {
		out = append(out, toTaskListSchema(&items[i]))
	}
	return out, nil
}

// Retrieve preloads every relation field carried on the retrieve schema —
// list never does, by construction, which is why list/retrieve are
// separate tags (plan section 5.5): it's the guarantee against N+1, not an
// implementation detail.
func (r *TaskResource) Retrieve(ctx context.Context, id int64) (*TaskRetrieveSchema, error) {
	q := r.DB(ctx)

	var m models.Task
	if err := q.First(&m, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "task", ID: id}
		}
		return nil, err
	}
	out := toTaskRetrieveSchema(&m)
	return &out, nil
}

func (r *TaskResource) Create(ctx context.Context, in TaskCreateSchema) (*TaskRetrieveSchema, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	m := models.Task{
		Title: in.Title,
		Done:  in.Done,
	}
	if err := r.DB(ctx).Create(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, m.ID)
}

func (r *TaskResource) Update(ctx context.Context, id int64, in TaskUpdateSchema) (*TaskRetrieveSchema, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	var m models.Task
	if err := r.DB(ctx).First(&m, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "task", ID: id}
		}
		return nil, err
	}
	m.Title = in.Title
	m.Done = in.Done
	if err := r.DB(ctx).Save(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, id)
}

func (r *TaskResource) Delete(ctx context.Context, id int64) error {
	res := r.DB(ctx).Delete(&models.Task{}, id)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return goninja.NotFound{Resource: "task", ID: id}
	}
	return nil
}

func (r *TaskResource) listHandler(w http.ResponseWriter, req *http.Request) {
	items, err := r.List(req.Context())
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, items)
}

func (r *TaskResource) retrieveHandler(w http.ResponseWriter, req *http.Request) {
	id, err := strconv.ParseInt(req.PathValue("id"), 10, 64)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}
	out, err := r.Retrieve(req.Context(), id)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

func (r *TaskResource) createHandler(w http.ResponseWriter, req *http.Request) {
	var in TaskCreateSchema
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	out, err := r.Create(req.Context(), in)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusCreated, out)
}

func (r *TaskResource) updateHandler(w http.ResponseWriter, req *http.Request) {
	id, err := strconv.ParseInt(req.PathValue("id"), 10, 64)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}
	var in TaskUpdateSchema
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	out, err := r.Update(req.Context(), id, in)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

func (r *TaskResource) deleteHandler(w http.ResponseWriter, req *http.Request) {
	id, err := strconv.ParseInt(req.PathValue("id"), 10, 64)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid id"})
		return
	}
	if err := r.Delete(req.Context(), id); err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// Register mounts list/retrieve/create/update/delete routes for
// Task under /tasks on mux.
func (r *TaskResource) Register(mux *http.ServeMux) {
	mux.HandleFunc("GET /tasks", r.listHandler)
	mux.HandleFunc("POST /tasks", r.createHandler)
	mux.HandleFunc("GET /tasks/{id}", r.retrieveHandler)
	mux.HandleFunc("PUT /tasks/{id}", r.updateHandler)
	mux.HandleFunc("DELETE /tasks/{id}", r.deleteHandler)
}
