// Code generated by goninja generate. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/caspel26/goninja"
	"github.com/caspel26/goninja/id"
	"github.com/caspel26/goninja/openapi"
	"gorm.io/gorm"

	"github.com/caspel26/goninja/examples/gin/models"
)

// TaskList is the shape returned by GET /tasks,
// one item per row of the "items" field of goninja.ListEnvelope.
type TaskList struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}

// TaskRetrieve is the shape returned by GET /tasks/{id}.
// A relation field (e.g. Author) is nested as that model's own Retrieve
// type, never the raw related struct — output types are always separate
// from the model, so a sensitive field can't leak into a response just
// because it exists on the related struct either. A relation field tagged
// "byid" instead exposes only the related model's ID,
// as "<field>_id" — no nesting, no Preload.
type TaskRetrieve struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}

// TaskCreate is the shape accepted by POST /tasks.
// `validate` tags (go-playground/validator syntax) are copied verbatim from
// the model field's own `validate` tag, and enforced by goninja.Validate
// before Create runs.
type TaskCreate struct {
	Title string `json:"title" validate:"required,max=200"`
	Done  bool   `json:"done"`
}

// TaskUpdate is the shape accepted by PUT /tasks/{id}.
type TaskUpdate struct {
	Title string `json:"title" validate:"required,max=200"`
	Done  bool   `json:"done"`
}

// TaskFilters is the shape parsed from GET /tasks
// query parameters: one exact-match pointer field
// per `filter`-tagged model field, plus Min/Max range pointers for numeric
// ones, plus Limit/Offset/Order shared by every model's list query. A nil
// field means "no filter" — List only adds a WHERE clause for the ones the
// caller actually set.
type TaskFilters struct {
	Done   *bool
	Limit  int
	Offset int
	// Order is a list-field JSON name, optionally "-"-prefixed for
	// descending (e.g. "-created_at"). Unknown field names are ignored.
	Order string
}

// taskOrderableColumns whitelists which query values
// "order" accepts — every list field, keyed and valued by its JSON name
// (assumed to match the actual DB column, per this model's `json` tags).
// Only ever indexed with a known key, never interpolated from user input
// directly, so this doubles as the SQL-injection guard for ORDER BY.
var taskOrderableColumns = map[string]string{
	"id":    "id",
	"title": "title",
	"done":  "done",
}

// taskInvalidIDMsg/taskIDQuery/
// taskContentTypeJSON/taskNotFoundDesc/
// taskRetrieveRef are shared across this file's
// handlers/resource methods (including OpenAPI() and its helpers below) to
// avoid repeating the same literal per call site — package-level, prefixed
// per model since several models can be generated into the same output
// package.
const (
	taskInvalidIDMsg    = "invalid id"
	taskIDQuery         = "id = ?"
	taskContentTypeJSON = "application/json"
	taskNotFoundDesc    = "Not found"
	taskRetrieveRef     = "#/components/schemas/TaskRetrieve"
)

func toTaskList(m *models.Task) TaskList {
	return TaskList{
		ID:    m.ID,
		Title: m.Title,
		Done:  m.Done,
	}
}

func toTaskRetrieve(m *models.Task) TaskRetrieve {
	return TaskRetrieve{
		ID:    m.ID,
		Title: m.Title,
		Done:  m.Done,
	}
}

// TaskResource is the generated GORM-backed CRUD resource for
// Task. Embeds goninja.BaseResource for a transaction-aware
// DB(ctx) and a configurable ErrorMapper.
type TaskResource struct {
	goninja.BaseResource
}

// TaskOption configures a TaskResource at
// construction time — see NewTaskResource. Build one with
// goninja.Actions to attach custom Actions right at construction, e.g.
// NewTaskResource(db, goninja.Actions(build, arg)).
type TaskOption func(*TaskResource)

// NewTaskResource builds a TaskResource bound to db,
// applying opts in order — see TaskOption. Safe to call with no
// opts at all; existing callers that never pass any keep working
// unchanged.
func NewTaskResource(db *gorm.DB, opts ...TaskOption) *TaskResource {
	r := &TaskResource{}
	r.SetDB(db)
	r.SetSelf(r)
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// TaskOps is the method set the generated handlers dispatch
// every request through. A type embedding TaskResource and
// overriding one of these methods is picked up
// automatically once wired in via SetSelf — see ops() below.
type TaskOps interface {
	List(ctx context.Context, f TaskFilters) ([]TaskList, int64, error)
	Retrieve(ctx context.Context, id string) (*TaskRetrieve, error)
	Create(ctx context.Context, in TaskCreate) (*TaskRetrieve, error)
	Update(ctx context.Context, id string, in TaskUpdate) (*TaskRetrieve, error)
	Delete(ctx context.Context, id string) error
}

// ops returns the TaskOps the generated handlers should call:
// r.Self() if it satisfies the interface (a wrapper type overriding one or
// more methods), otherwise r itself. r.Self() is r by default (set by
// NewTaskResource), so this is a no-op unless SetSelf was
// called again with a different value.
func (r *TaskResource) ops() TaskOps {
	if o, ok := r.Self().(TaskOps); ok {
		return o
	}
	return r
}

// List applies f's filters/ordering, counts the total matching rows before
// paginating, and returns Limit/Offset rows plus that total — never a
// Preload, by construction, which is why list/retrieve are separate tags:
// it's the guarantee against N+1, not an implementation detail.
func (r *TaskResource) List(ctx context.Context, f TaskFilters) ([]TaskList, int64, error) {
	q := r.DB(ctx).Model(&models.Task{})
	if f.Done != nil {
		q = q.Where("done = ?", *f.Done)
	}

	var total int64
	if err := q.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	if f.Order != "" {
		field, desc := strings.CutPrefix(f.Order, "-")
		if col, ok := taskOrderableColumns[field]; ok {
			dir := "ASC"
			if desc {
				dir = "DESC"
			}
			q = q.Order(col + " " + dir)
		}
	}

	var items []models.Task
	if err := q.Limit(f.Limit).Offset(f.Offset).Find(&items).Error; err != nil {
		return nil, 0, err
	}
	out := make([]TaskList, 0, len(items))
	for i := range items {
		out = append(out, toTaskList(&items[i]))
	}
	return out, total, nil
}

// Retrieve preloads every relation field carried on the retrieve type —
// list never does, by construction (see List above) — except one tagged
// "byid", which exposes only the related ID and so
// skips the Preload entirely.
func (r *TaskResource) Retrieve(ctx context.Context, id string) (*TaskRetrieve, error) {
	q := r.DB(ctx)

	var m models.Task
	if err := q.First(&m, taskIDQuery, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "task", ID: id}
		}
		return nil, err
	}
	out := toTaskRetrieve(&m)
	return &out, nil
}

func (r *TaskResource) Create(ctx context.Context, in TaskCreate) (*TaskRetrieve, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	m := models.Task{
		Title: in.Title,
		Done:  in.Done,
	}
	if m.ID == "" {
		m.ID = id.NewUUID()
	}
	if err := r.DB(ctx).Create(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, m.ID)
}

func (r *TaskResource) Update(ctx context.Context, id string, in TaskUpdate) (*TaskRetrieve, error) {
	if err := goninja.Validate(in); err != nil {
		return nil, err
	}
	var m models.Task
	if err := r.DB(ctx).First(&m, taskIDQuery, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, goninja.NotFound{Resource: "task", ID: id}
		}
		return nil, err
	}
	m.Title = in.Title
	m.Done = in.Done
	if err := r.DB(ctx).Save(&m).Error; err != nil {
		return nil, err
	}
	return r.Retrieve(ctx, id)
}

func (r *TaskResource) Delete(ctx context.Context, id string) error {
	res := r.DB(ctx).Where(taskIDQuery, id).Delete(&models.Task{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return goninja.NotFound{Resource: "task", ID: id}
	}
	return nil
}

// parseTaskFilters reads TaskFilters from the request's
// query parameters, keyed by each field's JSON name (plus "_min"/"_max" for
// numeric range filters). A value that fails to parse is a BadRequest.
func parseTaskFilters(req *http.Request) (TaskFilters, error) {
	q := req.URL.Query()
	var f TaskFilters

	if v := q.Get("done"); v != "" {
		parsed, err := strconv.ParseBool(v)
		if err != nil {
			return f, goninja.BadRequest{Detail: "invalid done"}
		}
		f.Done = &parsed
	}

	limit, offset, err := goninja.ParseLimitOffset(q)
	if err != nil {
		return f, err
	}
	f.Limit = limit
	f.Offset = offset

	// Reject an unknown order field here rather than ignoring it in List: a
	// typo would otherwise return the default order with a 200, which reads
	// as "sorted the way you asked" and is impossible to notice from the
	// response.
	if order := q.Get("order"); order != "" {
		field, _ := strings.CutPrefix(order, "-")
		if _, ok := taskOrderableColumns[field]; !ok {
			return f, goninja.BadRequest{
				Detail: "cannot order by \"" + field + "\"",
				Code:   "INVALID_ORDER_FIELD",
			}
		}
		f.Order = order
	}

	return f, nil
}

func (r *TaskResource) listHandler(w http.ResponseWriter, req *http.Request) {
	f, err := parseTaskFilters(req)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	items, total, err := r.ops().List(req.Context(), f)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, goninja.ListEnvelope[TaskList]{
		Items:  items,
		Total:  total,
		Limit:  f.Limit,
		Offset: f.Offset,
	})
}

func (r *TaskResource) retrieveHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: taskInvalidIDMsg})
		return
	}

	out, err := r.ops().Retrieve(req.Context(), id)
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// createHandler runs BeforeCreateHook/AfterCreateHook (hooks.go), if r's
// Self() implements them, in the same transaction as the create itself —
// a hook returning an error rolls the whole request back.
func (r *TaskResource) createHandler(w http.ResponseWriter, req *http.Request) {
	var in TaskCreate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*TaskRetrieve, error) {
		if h, ok := self.(goninja.BeforeCreateHook[TaskCreate]); ok {
			if err := h.BeforeCreate(ctx, &in); err != nil {
				return nil, err
			}
		}
		created, err := ops.Create(ctx, in)
		if err != nil {
			return nil, err
		}
		if h, ok := self.(goninja.AfterCreateHook[TaskRetrieve]); ok {
			if err := h.AfterCreate(ctx, created); err != nil {
				return nil, err
			}
		}
		return created, nil
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusCreated, out)
}

// updateHandler runs BeforeUpdateHook (hooks.go), if r's Self() implements
// it, in the same transaction as the update itself.
func (r *TaskResource) updateHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: taskInvalidIDMsg})
		return
	}

	var in TaskUpdate
	if err := json.NewDecoder(req.Body).Decode(&in); err != nil {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: "invalid JSON"})
		return
	}
	self, ops := r.Self(), r.ops()
	out, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (*TaskRetrieve, error) {
		if h, ok := self.(goninja.BeforeUpdateHook[TaskUpdate]); ok {
			if err := h.BeforeUpdate(ctx, &in); err != nil {
				return nil, err
			}
		}
		return ops.Update(ctx, id, in)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	goninja.RespondJSON(w, http.StatusOK, out)
}

// deleteHandler runs BeforeDeleteHook (hooks.go), if r's Self() implements
// it, in the same transaction as the delete itself.
func (r *TaskResource) deleteHandler(w http.ResponseWriter, req *http.Request) {
	id := req.PathValue("id")
	if id == "" {
		goninja.Respond(w, r.ErrorMapper(), goninja.BadRequest{Detail: taskInvalidIDMsg})
		return
	}

	self, ops := r.Self(), r.ops()
	_, err := goninja.InTransaction(req.Context(), r.DB(req.Context()), func(ctx context.Context) (struct{}, error) {
		if h, ok := self.(goninja.BeforeDeleteHook[string]); ok {
			if err := h.BeforeDelete(ctx, id); err != nil {
				return struct{}{}, err
			}
		}
		return struct{}{}, ops.Delete(ctx, id)
	})
	if err != nil {
		goninja.Respond(w, r.ErrorMapper(), err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// OpenAPI returns this resource's fragment of a merged OpenAPI document —
// the paths it mounts, the schemas those paths reference, and the security
// schemes any protected path's Security refers to (resolved via
// r.SecurityFor, the same logic Register's r.Protect calls enforce, so the
// two can't drift apart) — built from the same IR as the rest of this
// file, so they always match what List/Retrieve/Create/Update actually
// accept and return. Pass this resource to a goninja.API's Add method
// (alongside its Register(mux) call) to merge it in, or just pass it to
// API.Mount; see API.MountDocs.
func (r *TaskResource) OpenAPI() (map[string]*openapi.PathItem, map[string]openapi.Schema, map[string]openapi.SecurityScheme) {
	tags := r.OpenAPITags()
	if len(tags) == 0 {
		tags = []string{"Task"}
	}

	schemas := map[string]openapi.Schema{
		"TaskList": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"id":    {Type: "string"},
				"title": {Type: "string"},
				"done":  {Type: "boolean"},
			},
		},
		"TaskRetrieve": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"id":    {Type: "string"},
				"title": {Type: "string"},
				"done":  {Type: "boolean"},
			},
		},
		"TaskCreate": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"title": {Type: "string"},
				"done":  {Type: "boolean"},
			},
			Required: []string{"title"},
		},
		"TaskUpdate": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"title": {Type: "string"},
				"done":  {Type: "boolean"},
			},
			Required: []string{"title"},
		},
		"TaskListEnvelope": {
			Type: "object",
			Properties: map[string]openapi.Schema{
				"items":  {Type: "array", Items: &openapi.Schema{Ref: "#/components/schemas/TaskList"}},
				"total":  {Type: "integer", Format: "int64"},
				"limit":  {Type: "integer"},
				"offset": {Type: "integer"},
			},
		},
	}

	listParams := []openapi.Parameter{
		{Name: "done", In: "query", Schema: openapi.Schema{Type: "boolean"}},
		{Name: "limit", In: "query", Schema: openapi.Schema{Type: "integer"}},
		{Name: "offset", In: "query", Schema: openapi.Schema{Type: "integer"}},
		{Name: "order", In: "query", Schema: openapi.Schema{Type: "string"}},
	}

	idParam := openapi.Parameter{
		Name:     "id",
		In:       "path",
		Required: true,
		Schema:   openapi.Schema{Type: "string"},
	}

	cfg := r.resourceConfig()
	basePath := cfg.PathOr("/tasks")
	itemPath := basePath + "/{id}"

	paths := map[string]*openapi.PathItem{}
	securitySchemes := map[string]openapi.SecurityScheme{}

	if item := r.openAPIBasePathItem(cfg, tags, listParams, securitySchemes); item != nil {
		paths[basePath] = item
	}
	if item := r.openAPIItemPathItem(cfg, tags, idParam, securitySchemes); item != nil {
		paths[itemPath] = item
	}
	r.openAPIActionPaths(paths, basePath, idParam, tags, cfg, securitySchemes)

	return paths, schemas, securitySchemes
}

// openAPISecurity resolves route's Security requirement via r.SecurityFor
// and, if non-nil, merges its referenced SecurityScheme(s) into schemes —
// shared by every op builder below so each documents exactly what
// r.Protect enforces for that route.
func (r *TaskResource) openAPISecurity(route goninja.Route, cfg goninja.ResourceConfig, schemes map[string]openapi.SecurityScheme) []map[string][]string {
	reqs, s := r.SecurityFor(route, cfg)
	for name, scheme := range s {
		schemes[name] = scheme
	}
	return reqs
}

// openAPISecurityAction is openAPISecurity for an Action — via
// r.SecurityForAction, so a's own Auth (if set) is what gets documented,
// same as r.ProtectAction is what actually enforces it.
func (r *TaskResource) openAPISecurityAction(a goninja.Action, cfg goninja.ResourceConfig, schemes map[string]openapi.SecurityScheme) []map[string][]string {
	reqs, s := r.SecurityForAction(a, cfg)
	for name, scheme := range s {
		schemes[name] = scheme
	}
	return reqs
}

// openAPIBasePathItem builds the list/create *openapi.PathItem for
// "tasks" (nil if neither route is enabled) — split out of
// OpenAPI() to keep its cognitive complexity in check.
func (r *TaskResource) openAPIBasePathItem(cfg goninja.ResourceConfig, tags []string, listParams []openapi.Parameter, schemes map[string]openapi.SecurityScheme) *openapi.PathItem {
	item := &openapi.PathItem{}
	if cfg.RouteEnabled(goninja.RouteList) {
		item.Get = &openapi.Operation{
			Summary:    "List tasks",
			Tags:       tags,
			Parameters: listParams,
			Security:   r.openAPISecurity(goninja.RouteList, cfg, schemes),
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					taskContentTypeJSON: {Schema: openapi.Schema{Ref: "#/components/schemas/TaskListEnvelope"}},
				}},
			},
		}
	}
	if cfg.RouteEnabled(goninja.RouteCreate) {
		item.Post = &openapi.Operation{
			Summary:  "Create a task",
			Tags:     tags,
			Security: r.openAPISecurity(goninja.RouteCreate, cfg, schemes),
			RequestBody: &openapi.RequestBody{
				Required: true,
				Content: map[string]openapi.MediaType{
					taskContentTypeJSON: {Schema: openapi.Schema{Ref: "#/components/schemas/TaskCreate"}},
				},
			},
			Responses: map[string]openapi.Response{
				"201": {Description: "Created", Content: map[string]openapi.MediaType{
					taskContentTypeJSON: {Schema: openapi.Schema{Ref: taskRetrieveRef}},
				}},
				"422": {Description: "Validation error"},
			},
		}
	}
	if item.Get == nil && item.Post == nil {
		return nil
	}
	return item
}

// openAPIItemPathItem builds the retrieve/update/delete *openapi.PathItem
// for "tasks/{id}" (nil if none of the three routes is
// enabled) — split out of OpenAPI() to keep its cognitive complexity in
// check.
func (r *TaskResource) openAPIItemPathItem(cfg goninja.ResourceConfig, tags []string, idParam openapi.Parameter, schemes map[string]openapi.SecurityScheme) *openapi.PathItem {
	item := &openapi.PathItem{}
	if cfg.RouteEnabled(goninja.RouteRetrieve) {
		item.Get = &openapi.Operation{
			Summary:    "Retrieve a task",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			Security:   r.openAPISecurity(goninja.RouteRetrieve, cfg, schemes),
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					taskContentTypeJSON: {Schema: openapi.Schema{Ref: taskRetrieveRef}},
				}},
				"404": {Description: taskNotFoundDesc},
			},
		}
	}
	if cfg.RouteEnabled(goninja.RouteUpdate) {
		item.Put = &openapi.Operation{
			Summary:    "Update a task",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			Security:   r.openAPISecurity(goninja.RouteUpdate, cfg, schemes),
			RequestBody: &openapi.RequestBody{
				Required: true,
				Content: map[string]openapi.MediaType{
					taskContentTypeJSON: {Schema: openapi.Schema{Ref: "#/components/schemas/TaskUpdate"}},
				},
			},
			Responses: map[string]openapi.Response{
				"200": {Description: "OK", Content: map[string]openapi.MediaType{
					taskContentTypeJSON: {Schema: openapi.Schema{Ref: taskRetrieveRef}},
				}},
				"404": {Description: taskNotFoundDesc},
				"422": {Description: "Validation error"},
			},
		}
	}
	if cfg.RouteEnabled(goninja.RouteDelete) {
		item.Delete = &openapi.Operation{
			Summary:    "Delete a task",
			Tags:       tags,
			Parameters: []openapi.Parameter{idParam},
			Security:   r.openAPISecurity(goninja.RouteDelete, cfg, schemes),
			Responses: map[string]openapi.Response{
				"204": {Description: "No content"},
				"404": {Description: taskNotFoundDesc},
			},
		}
	}
	if item.Get == nil && item.Put == nil && item.Delete == nil {
		return nil
	}
	return item
}

// openAPIActionPaths adds a path entry for every r.Actions() action that
// carries a Summary, mounted the same way Register mounts it (base or
// "/{id}"-suffixed, then UrlPath) — split out of OpenAPI() to keep its
// cognitive complexity in check.
func (r *TaskResource) openAPIActionPaths(paths map[string]*openapi.PathItem, basePath string, idParam openapi.Parameter, tags []string, cfg goninja.ResourceConfig, schemes map[string]openapi.SecurityScheme) {
	for _, a := range r.Actions() {
		if a.Summary == "" {
			continue
		}
		p := basePath
		if a.Detail {
			p += "/{id}"
		}
		if a.UrlPath != "" {
			p += "/" + a.UrlPath
		}
		item, ok := paths[p]
		if !ok {
			item = &openapi.PathItem{}
			paths[p] = item
		}
		op := &openapi.Operation{Summary: a.Summary, Tags: tags, Responses: a.Responses, Security: r.openAPISecurityAction(a, cfg, schemes)}
		if a.Detail {
			op.Parameters = []openapi.Parameter{idParam}
		}
		switch a.Method {
		case http.MethodGet:
			item.Get = op
		case http.MethodPost:
			item.Post = op
		case http.MethodPut:
			item.Put = op
		case http.MethodDelete:
			item.Delete = op
		}
	}
}

// resourceConfig resolves r's ResourceConfig via r.Self(), the same
// dispatch hooks.go and ops() use: a wrapper implementing
// goninja.Configurer customizes it, otherwise every
// generated default applies.
func (r *TaskResource) resourceConfig() goninja.ResourceConfig {
	if c, ok := r.Self().(goninja.Configurer); ok {
		return c.Config()
	}
	return goninja.ResourceConfig{}
}

// Register mounts list/retrieve/create/update/delete routes for
// Task under /tasks on mux (any goninja.Router —
// *http.ServeMux, or an adapter for gin/echo/chi), or under r's
// ResourceConfig.Path/Routes override (see resourceConfig above) if one is
// set. Every handler is wrapped through r.Protect, which applies this
// resource's Config (global default auth + generic middleware, set via
// API.MountWithConfig — see config.go) combined with cfg's own per-route
// Auth override (ResourceConfig.Auth, keyed by Route); a resource mounted
// via plain API.Mount has a zero Config, so Protect is a no-op there.
// Every Action declared via SetActions is mounted last, on the same mux,
// at <path>[/{id}][/UrlPath] depending on its Detail/UrlPath, wrapped
// through r.ProtectAction instead (consults Action.Auth first). Before
// mounting anything, r.CheckStrictAuth panics if Config.StrictAuth is set
// and any route below has no explicit auth decision — a no-op otherwise.
func (r *TaskResource) Register(mux goninja.Router) {
	cfg := r.resourceConfig()
	path := cfg.PathOr("/tasks")
	crudRoutes := [...]struct {
		route   goninja.Route
		method  string
		path    string
		handler http.HandlerFunc
	}{
		{goninja.RouteList, "GET", path, r.listHandler},
		{goninja.RouteCreate, "POST", path, r.createHandler},
		{goninja.RouteRetrieve, "GET", path + "/{id}", r.retrieveHandler},
		{goninja.RouteUpdate, "PUT", path + "/{id}", r.updateHandler},
		{goninja.RouteDelete, "DELETE", path + "/{id}", r.deleteHandler},
	}
	var enabledRoutes []goninja.Route
	for _, rt := range crudRoutes {
		if cfg.RouteEnabled(rt.route) {
			enabledRoutes = append(enabledRoutes, rt.route)
		}
	}
	r.CheckStrictAuth(enabledRoutes, r.Actions(), cfg)
	for _, rt := range crudRoutes {
		if cfg.RouteEnabled(rt.route) {
			mux.HandleFunc(rt.method+" "+rt.path, r.Protect(rt.route, cfg, rt.handler))
		}
	}
	for _, a := range r.Actions() {
		p := path
		if a.Detail {
			p += "/{id}"
		}
		if a.UrlPath != "" {
			p += "/" + a.UrlPath
		}
		mux.HandleFunc(a.Method+" "+p, r.ProtectAction(a, cfg))
	}
}
